### ISSUE TITLE
Qos must be number

### ISSUE THREAD

**Issue by srmarjani** [mqttjs/MQTT.js#1026]
Hi
I've faced with a problem that took me some time to figure out.

Consider below codes as client and broker .
If i send qos config as string like "0" Nothing will be published.
So I find that qos must be number like 0

```javascript
var mqtt = require('mqtt')
var client = mqtt.connect('mqtt://127.0.0.1:1883')

client.on('connect', function () {
  client.publish('presence', 'Hello mqtt', { qos: 0})
})

client.on('offlien', () => {
  console.log('offlien')
});
client.on('close', () => {
  console.log('close')
});
```
Broker (from example of aedes-logging)
```javascript
'use strict'

var fs = require('fs')
var path = require('path')
var http = require('http')
var https = require('https')
var websocket = require('websocket-stream')
var net = require('net')
var tls = require('tls')
var aedes = require('aedes')
var logging = require('aedes-logging')
var instance = aedes()

var servers = [
  startHttp(),
  startHttps(),
  startNet(),
  startTLS()
]

logging({
  instance: instance,
  servers: servers
})

function startHttp () {
  var server = http.createServer()
  websocket.createServer({
    server: server
  }, instance.handle)
  server.listen(8880)
  return server
}

function startHttps () {
  var server = https.createServer({
    key: fs.readFileSync(path.join(__dirname, 'certs', 'key.pem')),
    cert: fs.readFileSync(path.join(__dirname, 'certs', 'cert.pem'))
  })
  websocket.createServer({
    server: server
  }, instance.handle)
  server.listen(8881)
  return server
}

function startNet () {
  return net.createServer(instance.handle).listen(1883)
}

function startTLS () {
  return tls.createServer({
    key: fs.readFileSync(path.join(__dirname, 'certs', 'key.pem')),
    cert: fs.readFileSync(path.join(__dirname, 'certs', 'cert.pem'))
  }, instance.handle).listen(8883)
}
```

**Comment by srmarjani** [comment]
In my Project I need multi connection so I used generic-pool.
Below my Implementation of pool and how i use it.

pool
```javascript
const genericPool = require("generic-pool");
const mqtt = require("mqtt");

const brokerUrl = "mqtt://127.0.0.1:1883";
const mqttOptions = {
  clean: true
}

const factory = {
  create: function () {
    return new Promise((resolve, reject) => {
      let client = mqtt.connect(brokerUrl, mqttOptions)
      client.on('connect', () => {
        resolve(client);
      });
      client.on('error', (error) => {
        client.end(true, () => {
          reject(error);
        })
      })
      client.on('offlien', () => {
        console.log('offlien')
      });
      client.on('close', () => {
        console.log('close')
      });
    });
  },
  destroy: function (client) {
    return new Promise((resolve) => {
      client.end(true, () => {
        resolve();
      })
    })
  }
};

const opts = {
  max: 10, // maximum size of the pool
  min: 5 // minimum size of the pool
};

const mqttPool = genericPool.createPool(factory, opts);

exports.mqttPool = mqttPool;
```
and in index I use node-cron to publish 1000 packet per job. I have 2 job.
```javascript
const mqttPool = require('./pool').mqttPool
const CronJob = require('cron').CronJob;
const pMap = require('p-map');

let job1 = new CronJob('* * * * * *', onTick);
let job2 = new CronJob('* * * * * *', onTick);

const publishCount = 1000;
let packets = [];

for (let i = 0; i <  publishCount; i++) {
  packets.push({
    topic: 'test',
    payload: 'payload',
    publishOption: {
      qos: "0"
    }
  })
}

function onTick() {
  let client = null;
  mqttPool.acquire()
  .then((result)=> {
    client = result;
    return pMap(packets, publish.bind(client), {concurrency: 10})
    .then(() => {
      mqttPool.release(client);
    })
    .catch(() => mqttPool.release(client))
  })
  .catch((error) => {
    console.log(error)
  })
}

function publish(packet) {
  let client = this;
  return new Promise((resolve) => {
    client.publish(packet.topic, packet.payload, packet.publishOption , (error) => {
      if(error) 
        console.log(error);
      resolve();  
    })
  });
}

job1.start();
job2.start();
```
In this scenario I get below error at broker side
```
{"level":40,"time":1578209772024,"msg":"Not supported","pid":19048,"hostname":"Dev","client":{"id":"mqttjs_7c63f82f"},"type":"Error","stack":"Error: Not supported\n    at Parser._parsePayload (C:\\Users\\razi.m\\Documents\\projects\\playground\\aedes-logging\\node_modules\\mqtt-packet\\parser.js:130:25)\n    at Parser.parse (C:\\Users\\razi.m\\Documents\\projects\\playground\\aedes-logging\\node_modules\\mqtt-packet\\parser.js:37:48)\n    at Socket.nextBatch (C:\\Users\\razi.m\\Documents\\projects\\playground\\aedes-logging\\node_modules\\aedes\\lib\\client.js:57:23)\n    at Socket.emit (events.js:189:13)\n    at emitReadable_ (_stream_readable.js:535:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","v":1}
```
and at clinet side connection close every time. 
to fix this problem I must send qos as number no as numberstring.

**Comment by YoDaMa** [comment]
This is useful if someone is also encountering this error but it is not a bug, and if you use TypeScript this will be enforced as the number 0 1 or 2.
