### ISSUE TITLE
Error: Invalid topic +C:/Program

### ISSUE THREAD

**Issue by basickarl** [mqttjs/MQTT.js#1071]
```
$ npx mqtt sub -t '+/LINE/+' -h '127.0.0.1' -v
Error: Invalid topic +C:/Program
    at MqttClient.subscribe (C:\Users\karl\Development\gateway\node_modules\mqtt\lib\client.js:529:28)
    at MqttClient.<anonymous> (C:\Users\karl\Development\gateway\node_modules\mqtt\bin\sub.js:90:12)
    at MqttClient.emit (events.js:228:7)
    at Readable.<anonymous> (C:\Users\karl\Development\gateway\node_modules\mqtt\lib\client.js:1449:14)
    at Readable.emit (events.js:223:5)
    at endReadableNT (C:\Users\karl\Development\gateway\node_modules\readable-stream\lib\_stream_readable.js:1010:12)    
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Any ideas? This happens if the broker is up or not. So the broker plays no role.

Running on Windows 10. 
"mqtt": "3.0.0",
node --version
v12.14.1

**Comment by jdiamond** [comment]
It looks like your topic is getting converted into a windows path. Are you using Git for Windows and the Git Bash shell that comes with that? If so, there is a way to disable that behavior:

https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line/34386471#34386471

**Comment by YoDaMa** [comment]
closed due to inactivity.
