### ISSUE TITLE
Exception when connecting with MQTT v5 to an MQTT v3.x broker

### ISSUE THREAD

**Issue by ralight** [mqttjs/MQTT.js#1073]
Connecting with MQTT v5.0 to a broker that does not support MQTT v5.0, e.g. Mosquitto 1.5.9, results in the exception below. This assumes that the broker responds to the CONNECT packet with a MQTT v3.x CONNACK packet that has the reason code set to "Connection Refused, unacceptable protocol version" rather than just terminating the connection. If it does terminate the connection, then the exception will not occur.

It is quite possible to handle this situation by checking for the CONNACK remaining length being set to 2, and the connack reason code being set to 1 (Connection Refused, unacceptable protocol version). MQTT v5.0 will always have remaining length set to at least 3.

```
internal/buffer.js:47
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt8 (internal/buffer.js:137:5)
    at BufferList.(anonymous function) [as readUInt8] (MQTT.js/node_modules/mqtt-packet/node_modules/bl/bl.js:274:58)
    at Parser._parseVarByteNum (MQTT.js/node_modules/mqtt-packet/parser.js:523:26)
    at Parser._parseProperties (MQTT.js/node_modules/mqtt-packet/parser.js:584:21)
    at Parser._parseConnack (MQTT.js/node_modules/mqtt-packet/parser.js:248:27)
    at Parser._parsePayload (MQTT.js/node_modules/mqtt-packet/parser.js:87:14)
    at Parser.parse (MQTT.js/node_modules/mqtt-packet/parser.js:39:41)
    at Writable.writable._write (MQTT.js/lib/client.js:293:12)
    at doWrite (MQTT.js/node_modules/readable-stream/lib/_stream_writable.js:428:64)
```

**Comment by YoDaMa** [comment]
So this looks like a feature request for catching errors from using MQTT v5 to connect to a MQTT v5 broker. Also, should the MQTTv5 client be a separate client totally, to optimize this package? Just a thought.

**Comment by mcollina** [comment]
I think this is _just_ a bug.
