### ISSUE TITLE
unsubscribe is not a function

### ISSUE THREAD

**Issue by exdevop** [mqttjs/MQTT.js#1161]
I have inplemented MQTT well but I am experiencing an issue with `unsubscribe` method. All other functions (`mqttCon.publish() , mqttCon.subscribe()... `) are working well except this. I have checked the spelling and even done `ctrl +click` and it takes me to the library implementation meaning it is the right method and referenced well yet I keep getting the error below. How can I solve it?

This is the line:  **`mqttCon.unsubscribe(topic)`**

`
TypeError: mqttCon.unsubscribe is not a function`

    at noopHandler (/home/dev/project-dir/src/mqtt/processMessage.js:5:13)
    at module.exports (/home/dev/project-dir/src/mqtt/processMessage.js:10:20)
    at MqttClient.client.on (/home/dev/project-dir/src/mqtt/mqttCon.js:16:13)
    at MqttClient.emit (events.js:189:13)
    at MqttClient._handlePublish (/home/dev/project-dir/node_modules/mqtt/lib/client.js:1271:12)
    at MqttClient._handlePacket (/home/dev/project-dir/node_modules/mqtt/lib/client.js:410:12)
    at work (/home/dev/project-dir/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/home/dev/project-dir/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/home/dev/project-dir/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/dev/project-dir/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)`

**Comment by YoDaMa** [comment]
there might be something wrong with the way you've installed it.... can you provide a longer snippet of your code to see how you create the MQTT connection?

**Comment by exdevop** [comment]
Here is my connection code `mqttCon.js`:
```
const mqtt = require('mqtt')
const processMessage = require('./processMessage')
const logger = require('../logConf')
const options = {
    host: '',
    port: '',
    username:'',
    password: '',
    protocol: ''
};
const client = mqtt.connect(options)
client.on("connect", function () {
    console.log("MQTT connected  with status: " + client.connected);
    if (client.connected) {
        client.on('message', (topic, message) => {
            processMessage(topic, String(message))
        })
    }
})
client.on('error', error => {
    console.log(error,'ERROR')
    logger.errorLogger.error(error)
})
client.on('reconnect', error => {
    console.log(error,'RECONNECT')
    logger.errorLogger.error(error)
})
client.on('close', error => {
    console.log(error,'CLOSE')
    logger.errorLogger.error(error)
})
client.on('disconnect', error => {
    console.log(error,'DISCONNECT')
    logger.errorLogger.error(error)
})
client.on('offline', error => {
    console.log(error,'OFFLINE')
    logger.errorLogger.error(error)
})
module.exports = client
```

@YoDaMa  this is the `processMessage.js` :

```
const mqttCon = require('./mqttCon')
const logger = require('../logConf')
let noopHandler = (topic, message) => {
    console.log(String(message))
    mqttCon.unsubscribe(topic)    //THIS IS WHERE THE ERROR IS OCCURRING *******************
}
module.exports = (topic, message) => {
    switch (topic) {
        case 'NOOOOOOOOOOOOOOOOOOOOOOOOP':
            return noopHandler(topic, message)
        case 'anotherTopic':
            // return handleAnotherTopic(String(message))
            return
        default:
            logger.errorLogger.error(new Error(`No handler for topic ${topic}`))

    }
}
```

**Comment by YoDaMa** [comment]
It's not immediately clear to me why this error is being hit. I'd recommend seeing what happens if you combine processMessage and mqttCon into one file...

**Comment by exdevop** [comment]
I asked this [here](https://stackoverflow.com/questions/63997685/nodejs-mqtt-unsubscribe-is-not-a-function/64001790#64001790) and got solution. Thank you
