### ISSUE TITLE
publishing to topic alias before setting alias causes crash ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by Steve-Mcl** [mqttjs/MQTT.js#1176]
version: 4.2.1

If I publish a payload with the topic set and topicAlias set first, this error does not occur.

If I publish a payload to a topicAlias before it is set, the below error occurs

I assume this is a bug as V4 shouldn't crash as the read me states...

> As a breaking change, by default a error handler is built into the MQTT.js client, so if any errors are emitted and the user has not created an event handler on the client for errors, the client will not break as a result of unhandled errors.

NOTES: This happens consistently when the publish is done against mosquitto.  When the publish is made against an EMQX broker, it disconnects (i seem to remember reading a disconnection is the correct outcome of publishing to an unset topic alias? - or perhaps i am mistaking that with exceeding `receiveMaximum` or `maximumPacketSize`?)

 

### The error...
```
Exception has occurred: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
  at boundsError (internal/buffer.js:74:11)
    at Buffer.readUInt8 (internal/buffer.js:242:5)
    at BufferListStream.BufferList.<computed> [as readUInt8] (node_modules\mqtt-packet\node_modules\bl\BufferList.js:377:60)
    at Parser._parseVarByteNum (node_modules\mqtt-packet\parser.js:553:28)
    at Parser._parseProperties (node_modules\mqtt-packet\parser.js:620:25)
    at Parser._parseDisconnect (node_modules\mqtt-packet\parser.js:447:31)
    at Parser._parsePayload (node_modules\mqtt-packet\parser.js:124:16)
    at Parser.parse (node_modules\mqtt-packet\parser.js:43:45)
    at Writable.writable._write (node_modules\mqtt\lib\client.js:334:12)
    at doWrite (node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:714:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

```

### Steps to re-create...

* do a clean connect
* publish a message with empty topic and a topicAlias
```
client.publish('', '1602019335421', { 
  "qos":1,"retain":false,
  "properties":{
    "topicAlias":1,"contentType":"contentType can describe stuff",
    "userProperties":{"time":"2020-10-06T21:22:15.421Z"}
  }
})
```

### Other

![image](https://user-images.githubusercontent.com/44235289/95262129-7aad7e00-0823-11eb-9399-f79d13ac44d4.png)

AB#8508445

**Comment by YoDaMa** [comment]
This is an interesting bug that might be specific to the mqtt-packet sub-dependency... or it might be an issue with the mosquitto broker.

**Comment by ogis-yamazaki** [comment]
I had the same problem.

- mosquitto version 1.6.11
- mqttjs version 4.2.6

## source

```js
'use strict'

const mqtt = require('mqtt');

const connectOptions = {
    clean: true,
    username: 'hoge',
    password: 'hoge',
    protocolVersion: 5
}

const client = mqtt.connect('mqtt://localhost:1883', connectOptions);

client.on('connect', function (packet) {
    console.log('client event:connect, sessionPresent:' + packet.sessionPresent);
    setImmediate(function () {
        client.publish('', 'example', { qos: 1 , properties: { topicAlias: 1 }}, (err, result) => {
            if (err) {
                console.error(err);
                client.end(true)
            }
        })
    })
});
client.on('close', function () {
    console.log('client event:close');
    client.end(true)
})

client.on('error', function (err) {
    console.log('client event:error');
    console.error(err);
    client.end(true)
})

```

## client log

```
  mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: options.protocol mqtt +0ms
  mqttjs:client MqttClient :: options.protocolVersion 5 +0ms
  mqttjs:client MqttClient :: options.username hoge +0ms
  mqttjs:client MqttClient :: options.keepalive 60 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized undefined +0ms
  mqttjs:client MqttClient :: clientId mqttjs_035b74af +0ms
  mqttjs:client MqttClient :: setting up stream +1ms
  mqttjs:client _setupStream :: calling method to clear reconnect +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupStream :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for mqtt +4ms
  mqttjs:tcp port 1883 and host localhost +0ms
  mqttjs:client _setupStream :: pipe stream to writable stream +3ms
  mqttjs:client _setupStream: sending packet `connect` +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'connect' } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +19ms
  mqttjs:client writable stream :: parsing buffer +3ms
  mqttjs:client parser :: on packet push to packets array. +1ms
  mqttjs:client work :: getting next packet in queue +0ms
  mqttjs:client work :: packet pulled from queue +1ms
  mqttjs:client _handlePacket :: emitting packetreceive +0ms
  mqttjs:client _handleConnack +0ms
  mqttjs:client _setupPingTimer :: keepalive 60 (seconds) +0ms
  mqttjs:client _resubscribe +0ms
  mqttjs:client connect :: sending queued packets +1ms
  mqttjs:client deliver :: entry undefined +0ms
client event:connect, sessionPresent:false
  mqttjs:client publish :: message `example` to topic `` +1ms
  mqttjs:client publish :: qos 1 +0ms
  mqttjs:client MqttClient:publish: packet cmd: publish +0ms
  mqttjs:client _sendPacket :: (mqttjs_035b74af) ::  start +0ms
  mqttjs:client storeAndSend :: store packet with cmd publish to outgoingStore +0ms
  mqttjs:client nop :: undefined +0ms
  mqttjs:client sendPacket :: packet: {
  mqttjs:client   cmd: 'publish',
  mqttjs:client   topic: '',
  mqttjs:client   payload: 'example',
  mqttjs:client   qos: 1,
  mqttjs:client   retain: false,
  mqttjs:client   messageId: 61569,
  mqttjs:client   dup: false,
  mqttjs:client   properties: { topicAlias: 1 }
  mqttjs:client } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  mqttjs:client _sendPacket :: (mqttjs_035b74af) ::  end +0ms
  mqttjs:client writable stream :: parsing buffer +1ms
internal/buffer.js:79
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:79:11)
    at Buffer.readUInt8 (internal/buffer.js:247:5)
    at BufferListStream.BufferList.<computed> [as readUInt8] (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/bl/BufferList.js:377:60)
    at Parser._parseVarByteNum (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt-packet/parser.js:552:28)
    at Parser._parseProperties (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt-packet/parser.js:623:25)
    at Parser._parseDisconnect (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt-packet/parser.js:445:31)
    at Parser._parsePayload (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt-packet/parser.js:122:16)
    at Parser.parse (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt-packet/parser.js:43:45)
    at Writable.writable._write (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/mqtt/lib/client.js:334:12)
    at doWrite (/home/ymzk/msgpub/mqttv5_js_sample/node_modules/readable-stream/lib/_stream_writable.js:409:139) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```


## mosquitto log

```
 1月 20 16:07:55 YMZK mosquitto[714793]: 1611126475: Socket error on client cid1, disconnecting.
 1月 20 16:23:50 YMZK systemd[1]: Stopping Mosquitto MQTT Broker daemon...
 1月 20 16:23:50 YMZK mosquitto[714793]: 1611127430: mosquitto version 1.6.11 terminating
 1月 20 16:23:50 YMZK systemd[1]: mosquitto.service: Succeeded.
 1月 20 16:23:50 YMZK systemd[1]: Stopped Mosquitto MQTT Broker daemon.
 1月 20 16:23:50 YMZK systemd[1]: Started Mosquitto MQTT Broker daemon.
 1月 20 16:23:50 YMZK mosquitto[716043]: 1611127430: mosquitto version 1.6.11 starting
 1月 20 16:23:50 YMZK mosquitto[716043]: 1611127430: Config loaded from /etc/mosquitto/mosquitto.conf.
 1月 20 16:23:50 YMZK mosquitto[716043]: 1611127430: Opening ipv4 listen socket on port 1883.
 1月 20 16:23:50 YMZK mosquitto[716043]: 1611127430: mosquitto version 1.6.11 running
 1月 20 16:23:56 YMZK mosquitto[716043]: 1611127436: New connection from 127.0.0.1 on port 1883.
 1月 20 16:23:56 YMZK mosquitto[716043]: 1611127436: New client connected from 127.0.0.1 as mqttjs_035b74af (p5, c1, k60, u'hoge').
 1月 20 16:23:56 YMZK mosquitto[716043]: 1611127436: No will message specified.
 1月 20 16:23:56 YMZK mosquitto[716043]: 1611127436: Sending CONNACK to mqttjs_035b74af (0, 0)
 1月 20 16:23:56 YMZK mosquitto[716043]: 1611127436: Socket error on client mqttjs_035b74af, disconnecting.
```

**Comment by ogis-yamazaki** [comment]
mosquitto version 1.6.11

I experimented with mosquitto.
mosquitto returned the following DISCONNECT packet

(hex)
```
e0 01 94
```

Property Length seems to be omitted.

Reading the following document, I think omissions are allowed.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901210
```
3.14.2.2.1 Property Length
The length of Properties in the DISCONNECT packet Variable Header encoded as a Variable Byte Integer. If the Remaining Length is less than 2, a value of 0 is used.
```

**Comment by redboltz** [comment]
It seems that https://github.com/mqttjs/mqtt-packet/pull/78 would fix the issue.
