### ISSUE TITLE
yarn 2: Error: mqtt tried to access duplexify, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by francisu** [mqttjs/MQTT.js#1215]
The message below when running 4.2.3 in a yarn 2/pnp environment.

To fix this locally, add the following to your .yarnrc.yml file:

```
packageExtensions:
  mqtt@*:
    dependencies:
      duplexify: ^4.1.1
```

The mqtt library should be modified to add this dependency.

-----------------------

```
Error: mqtt tried to access duplexify, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: duplexify (via "duplexify")
Required by: mqtt@npm:4.2.3 (via /Users/francis/d/IdeaProjects/product/.yarn/cache/mqtt-npm-4.2.3-f99e660993-1c5e2a32ab.zip/node_modules/mqtt/lib/connect/)

Require stack:
- /Users/francis/d/IdeaProjects/product/.yarn/cache/mqtt-npm-4.2.3-f99e660993-1c5e2a32ab.zip/node_modules/mqtt/lib/connect/ws.js
- /Users/francis/d/IdeaProjects/product/.yarn/cache/mqtt-npm-4.2.3-f99e660993-1c5e2a32ab.zip/node_modules/mqtt/lib/connect/index.js
- /Users/francis/d/IdeaProjects/product/.yarn/cache/mqtt-npm-4.2.3-f99e660993-1c5e2a32ab.zip/node_modules/mqtt/mqtt.js
- /Users/francis/d/IdeaProjects/product/.yarn/cache/aws-iot-device-sdk-npm-2.2.6-53d2de1554-60ff3ccbb2.zip/node_modules/aws-iot-device-sdk/device/index.js
- /Users/francis/d/IdeaProjects/product/.yarn/cache/aws-iot-device-sdk-npm-2.2.6-53d2de1554-60ff3ccbb2.zip/node_modules/aws-iot-device-sdk/index.js
- /Users/francis/d/IdeaProjects/product/packages/universal/apolloClient/subscriptionHandshakeLink.ts
- /Users/francis/d/IdeaProjects/product/packages/universal/apolloClient/graphQlClient.ts
- /Users/francis/d/IdeaProjects/product/packages/universal/pipeline/pipelineManager.ts
- /Users/francis/d/IdeaProjects/product/packages/universal/dynamoAccess.ts
- /Users/francis/d/IdeaProjects/product/packages/server/indexSupport.ts
- /Users/francis/d/IdeaProjects/product/packages/server/clientManagerServer.ts
- /Users/francis/d/IdeaProjects/product/packages/server/devSetup.ts
    at internalTools_makeError (/Users/francis/d/IdeaProjects/product/.pnp.js:41598:34)
    at resolveToUnqualified (/Users/francis/d/IdeaProjects/product/.pnp.js:42558:23)
    at resolveRequest (/Users/francis/d/IdeaProjects/product/.pnp.js:42650:29)
    at Object.resolveRequest (/Users/francis/d/IdeaProjects/product/.pnp.js:42728:26)
    at Function.external_module_.Module._resolveFilename (/Users/francis/d/IdeaProjects/product/.pnp.js:41831:34)
    at Function.external_module_.Module._load (/Users/francis/d/IdeaProjects/product/.pnp.js:41696:48)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/francis/d/IdeaProjects/product/.yarn/cache/mqtt-npm-4.2.3-f99e660993-1c5e2a32ab.zip/node_modules/mqtt/lib/connect/ws.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
```

**Comment by francisu** [comment]
Seems like this was fixed.
