### ISSUE TITLE
Cannot parse topic and ERR_BUFFER_OUT_OF_BOUNDS.

### ISSUE THREAD

**Issue by ProtonGustave** [mqttjs/MQTT.js#1228]
From time to time(in a course of a day) i see multiple errors like that:
```
app_1  | MQTT error Error: Cannot parse topic
app_1  |     at Parser._parsePublish (/app/node_modules/mqtt-packet/parser.js:282:29)
app_1  |     at Parser._parsePayload (/app/node_modules/mqtt-packet/parser.js:102:16)
app_1  |     at Parser.parse (/app/node_modules/mqtt-packet/parser.js:46:45)
app_1  |     at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:334:12)
app_1  |     at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
app_1  |     at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
app_1  |     at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
app_1  |     at Socket.ondata (_stream_readable.js:716:22)
app_1  |     at Socket.emit (events.js:315:20)
app_1  |     at addChunk (_stream_readable.js:295:12)
app_1  | internal/buffer.js:75
app_1  |     throw new ERR_BUFFER_OUT_OF_BOUNDS();
```
then
```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
app_1  |     at boundsError (internal/buffer.js:75:11)
app_1  |     at Buffer.readUInt8 (internal/buffer.js:243:5)
app_1  |     at BufferListStream.BufferList.<computed> [as readUInt8] (/app/node_modules/bl/BufferList.js:377:60)
app_1  |     at Parser._parseVarByteNum (/app/node_modules/mqtt-packet/parser.js:562:28)
app_1  |     at Parser._parseLength (/app/node_modules/mqtt-packet/parser.js:73:25)
app_1  |     at Parser.parse (/app/node_modules/mqtt-packet/parser.js:46:45)
app_1  |     at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:334:12)
app_1  |     at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
app_1  |     at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
app_1  |     at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11) {
app_1  |   code: 'ERR_BUFFER_OUT_OF_BOUNDS'
```
and process crash.
So i changed `mqtt-packet/parser.js` code to see what's up(277 line, function _parsePublish):
```
 if (packet.topic === null) {
            console.log(packet);
            console.log(this._list);
            console.log('utf8', this._list.toString('utf8'));
            console.log('hex', this._list.toString('hex'));
            return this._emitError(new Error('Cannot parse topic'))
    }
```
One example of output(there is a lot of messages like that): [logs](https://github.com/mqttjs/MQTT.js/files/5693992/new.txt)
What's wrong? Can i at least somehow prevent process crash?

AB#8978292

**Comment by Steve-Mcl** [comment]
Hello, I am seeing exact same error.

I see that `mqtt-packet` [has a fix for this issue](https://github.com/mqttjs/mqtt-packet/pull/100) for this issue since 12 Feb but MQTT.JS V4.2.6 on NPM still references mqtt-packet@6.6.0 (see [here](https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/package.json#L71)) 

I have noted that MQTT.JS current github package.json now references mqtt-packet@6.8.0 (which does contain this bug fix) 

So I guess to cut a long story short, is there a chance will MQTT.JS be released on NPM with this fix in the near future please?

Thank you.

**Comment by YoDaMa** [comment]
Let me know if the new release fixed this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Steve-Mcl** [comment]
@YoDaMa works for me.
