### ISSUE TITLE
vite support

### ISSUE THREAD

**Issue by jahnli** [mqttjs/MQTT.js#1269]
Currently used on vite, node variables such as global are shown to be wrong

Will Vue Vite be supported

**Comment by chartinger** [comment]
You can already use this library with these changes to your code (ts):

* Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
* Add `"skipLibCheck": true` to your `tsconfig.json`
* Create a `shims-mqtt.d.ts` with 
  ```
  declare module 'mqtt/dist/mqtt.min' {
    import MQTT from 'mqtt'
    export = MQTT
  }
  ```

**Comment by Jairos2015** [comment]
It works for js environment (Vite + vue3 + mqtt).
import * as mqtt from 'mqtt/dist/mqtt.min';

Thank you.

**Comment by waytoviva** [comment]
> declare module 'mqtt/dist/mqtt.min' {
>   import MQTT from 'mqtt'
>   export = MQTT
> }

It works.Before this, shown "global  is not defined"

**Comment by YoDaMa** [comment]
> You can already use this library with these changes to your code (ts):
> 
> * Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
> * Add `"skipLibCheck": true` to your `tsconfig.json`
> * Create a `shims-mqtt.d.ts` with
>   ```
>   declare module 'mqtt/dist/mqtt.min' {
>     import MQTT from 'mqtt'
>     export = MQTT
>   }
>   ```

@chartinger these are good instructions. Do you know how to test that vite would be supported automatically, i.e. adding it to our Github Actions testing process? If so, we could more formally support vite for this package.

**Comment by chenzesam** [comment]
> You can already use this library with these changes to your code (ts):
> 
> * Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
> * Add `"skipLibCheck": true` to your `tsconfig.json`
> * Create a `shims-mqtt.d.ts` with
>   ```
>   declare module 'mqtt/dist/mqtt.min' {
>     import MQTT from 'mqtt'
>     export = MQTT
>   }
>   ```

i use this for my project, but i got error ```mqtt.min.js:1 Uncaught TypeError: n.createConnection is not a function``` when i use ```connect``` api, who can help me?

**Comment by chenzesam** [comment]
> > You can already use this library with these changes to your code (ts):
> > 
> > * Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
> > * Add `"skipLibCheck": true` to your `tsconfig.json`
> > * Create a `shims-mqtt.d.ts` with
> >   ```
> >   declare module 'mqtt/dist/mqtt.min' {
> >     import MQTT from 'mqtt'
> >     export = MQTT
> >   }
> >   ```
> 
> i use this for my project, but i got error `mqtt.min.js:1 Uncaught TypeError: n.createConnection is not a function` when i use `connect` api, who can help me?

oh, this is my error, i send the wrong url argument like ```htpp://``` so mqtt use ```net``` to connect...

**Comment by nerdyman** [comment]
Anyone know of an equivalent workaround for `async-mqtt`?

**Comment by BlakeTheAwesome** [comment]
> > i use this for my project, but i got error `mqtt.min.js:1 Uncaught TypeError: n.createConnection is not a function` when i use `connect` api, who can help me?
> 
> oh, this is my error, i send the wrong url argument like `htpp://` so mqtt use `net` to connect...


For anyone else running into this, it appears this library always tries to use the node `net` library when connecting with the `mqtt` protocol (selected by default if you have an `http` address).
I worked around the issue by connecting with a `ws://` protocol and adding an appropriate listener to my broker (`mosquitto`):
```
listener 8883
protocol websockets
```

**Comment by icsaba** [comment]
i just added 
`resolve: {
    alias: {
      mqtt: 'mqtt/dist/mqtt.js',
    },
  },` to my vite config, and it works!
  
  if you are using webtest runner, then add it in the webtest runner config too:
  
  ```
 import { fromRollup } from '@web/dev-server-rollup';
import pluginAlias from '@rollup/plugin-alias';

const alias = fromRollup(pluginAlias);
....
    plugins: [
    alias({
      entries: {
        mqtt: '.vite/mqtt.js',
      }
    }),
  ],
  ```

**Comment by shba007** [comment]
How to use mqtt in nuxt.js

**Comment by donkeylmx** [comment]
I`m not understand why  `mqtt.min.js:1 Uncaught TypeError: n.createConnection is not a function` happened in 4.3.7 version but success in 4.0.1.

**Comment by gmlewis** [comment]
I tried to follow the directions in this thread to upgrade the `emitter-io` package to the latest `mqtt` version here:
https://github.com/emitter-io/javascript/compare/master...gmlewis:master

but I still get this error in the browser:

```
[vite] connecting...
[vite] connected.
_stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/.pnpm/readable-stream@3.6.0/node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-OO5LXEG7.js?v=b2fd5b38:26:50)
    at node_modules/.pnpm/readable-stream@3.6.0/node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-OO5LXEG7.js?v=b2fd5b38:26:50)
    at node_modules/.pnpm/mqtt@4.3.7/node_modules/mqtt/lib/store.js (store.js:8:18)
    at __require (chunk-OO5LXEG7.js?v=b2fd5b38:26:50)
    at node_modules/.pnpm/mqtt@4.3.7/node_modules/mqtt/lib/client.js (client.js:7:15)
    at __require (chunk-OO5LXEG7.js?v=b2fd5b38:26:50)
    at node_modules/.pnpm/mqtt@4.3.7/node_modules/mqtt/lib/connect/index.js (index.js:3:20)
    at __require (chunk-OO5LXEG7.js?v=b2fd5b38:26:50)
```

Does anyone see what I'm doing wrong?

(I tried putting the `shims-mqtt.d.ts` file in both `lib` and the top-level dir, but neither worked.)

**Comment by bfritscher** [comment]
after 4.01 use ws:// or wss:// for your server url not mqtt.

**Comment by rogeriocassares** [comment]
Hi @everyone and @chartinger ! 

I could not active tô running your comments usina React.

Please could you help me?


Thanks!

**Comment by shba007** [comment]
> Hi @everyone and @chartinger !
> 
> I could not active tô running your comments usina React.
> 
> Please could you help me?
> 
> Thanks!

1. Install [mqtt](https://www.npmjs.com/package/mqtt) [precompiled-mqtt](https://www.npmjs.com/package/precompiled-mqtt) using npm or yarn
2. Copy the lib folder from node_modules/mqtt to node_modules/precompiled-mqtt
3. Use **import { connect } from "precompiled-mqtt"** to use mqtt

This is the easiest way to get started with mqtt. 
Other possible way is to install mqtt and compile manually. The instructions are given here [Webpack Bundling](https://github.com/mqttjs/MQTT.js#Webpack)

**Comment by onepisYa** [comment]
> You can already use this library with these changes to your code (ts):
> 
> * Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
> * Add `"skipLibCheck": true` to your `tsconfig.json`
> * Create a `shims-mqtt.d.ts` with
>   ```
>   declare module 'mqtt/dist/mqtt.min' {
>     import MQTT from 'mqtt'
>     export = MQTT
>   }
>   ```

vite + vue 2.7.10 + ts + pnpm

other than the above ,we can try

```zsh
pnpm i --save mqtt-packet
```

**Comment by rogeriocassares** [comment]
Hi @onepisYa , this also should works using react and not vue?

What the `shims-mqtt.d.ts` means to be? It works for react too?


Many Thanks!

**Comment by timstrasser** [comment]
> > > i use this for my project, but i got error `mqtt.min.js:1 Uncaught TypeError: n.createConnection is not a function` when i use `connect` api, who can help me?
> > 
> > 
> > oh, this is my error, i send the wrong url argument like `htpp://` so mqtt use `net` to connect...
> 
> For anyone else running into this, it appears this library always tries to use the node `net` library when connecting with the `mqtt` protocol (selected by default if you have an `http` address). I worked around the issue by connecting with a `ws://` protocol and adding an appropriate listener to my broker (`mosquitto`):
> 
> ```
> listener 8883
> protocol websockets
> ```

After doing that, I get `ReferenceError: WebSocket is not defined`... I'm using NUXT 3.

**Comment by Anubarak** [comment]
I always receive the error
```
index.6a90cf57.js:formatted:70800 Uncaught ReferenceError: Buffer is not defined
    at index.6a90cf57.js:formatted:70800:35
    at requireConstants (index.6a90cf57.js:formatted:70914:6)
    at requireParser (index.6a90cf57.js:formatted:70925:13)
    at requireMqtt (index.6a90cf57.js:formatted:72272:19)
    at requireClient (index.6a90cf57.js:formatted:72551:13)
    at requireConnect (index.6a90cf57.js:formatted:75156:15)
    at index.6a90cf57.js:formatted:75615:28
    at index.6a90cf57.js:formatted:75617:6
    at index.6a90cf57.js:formatted:75995:2
```

How were you all able to get rid of that?

**Comment by FrodoTrash** [comment]
any updates on this? Using Nuxt3 gives errors

**Comment by touxing** [comment]
> You can already use this library with these changes to your code (ts):
> 
> * Use `import * as mqtt from 'mqtt/dist/mqtt.min';`
> * Add `"skipLibCheck": true` to your `tsconfig.json`
> * Create a `shims-mqtt.d.ts` with
>   ```
>   declare module 'mqtt/dist/mqtt.min' {
>     import MQTT from 'mqtt'
>     export = MQTT
>   }
>   ```

It's useful. Thank you!

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out

**Comment by setpixel** [comment]
@robertsLando With your examples in Vite, it works when you run dev, but it does not work when you run build. 

`[plugin:vite:resolve] Module "url" has been externalized for browser compatibility, imported by "C:/Users/setpi/Documents/information-display/node_modules/mqtt/build/src/lib/connect/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.`

**Comment by robertsLando** [comment]
@setpixel Check vite-webpack in examples folder, that example works for both
