### ISSUE TITLE
Lots of vulnerabilities on master and test do not work. 

### ISSUE THREAD

**Issue by JimmyBjorklund** [mqttjs/MQTT.js#1287]
Audit give lots of issues, i would provide a pr but the test do not work at the moment, 
up to date, audited 1126 packages in 12s

47 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (3 low, 6 moderate, 7 high, 3 critical)

Failing tests:
---------------------|---------|----------|---------|---------|--------------------------------------------------------------------------------------------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------|---------|----------|---------|---------|--------------------------------------------------------------------------------------------------------
All files            |   88.29 |    82.27 |   86.89 |   88.73 |
 MQTT.js             |     100 |      100 |     100 |     100 |
  mqtt.js            |     100 |      100 |     100 |     100 |
 MQTT.js/lib         |   95.94 |     87.9 |   95.83 |   96.35 |
  client.js          |   95.95 |    88.56 |   95.24 |   96.41 | 18,135,439,490,746-747,751,755,767,934-935,1282-1284,1331-1333,1347-1349,1374,1469,1504-1506,1534-1535
  store.js           |   94.44 |    70.83 |     100 |   94.44 | 22,95-96
  validations.js     |     100 |      100 |     100 |     100 |
 MQTT.js/lib/connect |   60.87 |    65.03 |   53.85 |   61.67 |
  index.js           |   88.89 |    86.21 |     100 |   88.89 | 19-23,96-100,125
  tcp.js             |     100 |      100 |     100 |     100 |
  tls.js             |   94.74 |    90.91 |     100 |   94.74 | 21
  ws.js              |   33.88 |    40.58 |   29.41 |   34.75 | 58-84,102-110,124-248,252

**Comment by YoDaMa** [comment]
@LaurentGoderre  and @JimmyBjorklund , could you try the recently released 4.2.7 and let me know if things look good. The vulnerabilities that are unresolved should all be dev dependencies, which will be addressed but are not part of the released package.

**Comment by JimmyBjorklund** [comment]
I seem to have some strange issue with git it cannot find the tag for v4.2.7 or v4.2.8, i can find v4.2.6 just fine. But i can see them on github, When running on master i still get two failing test case

  1) Websocket Client
       auto reconnect
         should resend in-flight QoS 1 publish messages from the client:
     Uncaught Error: write after end
      at writeAfterEnd (node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:288:12)
      at Connection.Writable.write (node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:332:20)
      at Connection.<computed> [as pingresp] (node_modules/mqtt-connection/connection.js:83:10)
      at Connection.<anonymous> (test/server_helpers_for_client_tests.js:86:20)
      at Connection.emitPacket (node_modules/mqtt-connection/connection.js:10:8)
      at addChunk (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Connection.Readable.push (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Connection.Duplexify._forward (node_modules/duplexify/index.js:170:26)
      at DestroyableTransform.onreadable (node_modules/duplexify/index.js:134:10)
      at emitReadable_ (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:504:10)
      at emitReadable (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:498:62)
      at addChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:29)
      at readableAddChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at DestroyableTransform.Readable.push (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at DestroyableTransform.Transform.push (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at Parser.push (node_modules/mqtt-connection/lib/parseStream.js:19:12)
      at Parser._newPacket (node_modules/mqtt-packet/parser.js:699:12)
      at Parser.parse (node_modules/mqtt-packet/parser.js:43:45)
      at DestroyableTransform.process [as _transform] (node_modules/mqtt-connection/lib/parseStream.js:14:17)
      at DestroyableTransform.Transform._read (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
      at doWrite (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
      at writeOrBuffer (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
      at DestroyableTransform.Writable.write (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Socket.ondata (_stream_readable.js:719:22)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:284:9)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  2) Websocket Client
       auto reconnect
         should resend in-flight QoS 2 publish messages from the client:
     Uncaught Error: write after end
      at writeAfterEnd (node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:288:12)
      at Connection.Writable.write (node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:332:20)
      at Connection.<computed> [as pingresp] (node_modules/mqtt-connection/connection.js:83:10)
      at Connection.<anonymous> (test/server_helpers_for_client_tests.js:86:20)
      at Connection.emitPacket (node_modules/mqtt-connection/connection.js:10:8)
      at addChunk (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Connection.Readable.push (node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Connection.Duplexify._forward (node_modules/duplexify/index.js:170:26)
      at DestroyableTransform.onreadable (node_modules/duplexify/index.js:134:10)
      at emitReadable_ (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:504:10)
      at emitReadable (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:498:62)
      at addChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:29)
      at readableAddChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at DestroyableTransform.Readable.push (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at DestroyableTransform.Transform.push (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at Parser.push (node_modules/mqtt-connection/lib/parseStream.js:19:12)
      at Parser._newPacket (node_modules/mqtt-packet/parser.js:699:12)
      at Parser.parse (node_modules/mqtt-packet/parser.js:43:45)
      at DestroyableTransform.process [as _transform] (node_modules/mqtt-connection/lib/parseStream.js:14:17)
      at DestroyableTransform.Transform._read (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
      at doWrite (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
      at writeOrBuffer (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
      at DestroyableTransform.Writable.write (node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Socket.ondata (_stream_readable.js:719:22)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:284:9)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)


And security warnings 
19 vulnerabilities (3 low, 6 moderate, 7 high, 3 critical)

**Comment by YoDaMa** [comment]
going to close this because in terms of security vulnerability in the pacakge (not dev vulnerabilities), there are none currently. 

For failing WS test, yes some of the tests are currently flakey. We are going to throw them out and design better tests for vNext. You can offer your feedback or ideas for better tests here: https://github.com/mqttjs/MQTT.js/discussions/1324
