### ISSUE TITLE
Hi~,  When I install mqtt(4.3.6) package, will appear Error, I don't know why.

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [mqttjs/MQTT.js#1434]
`ERROR in ./~/mqtt/lib/client.js
Module parse failed: D:\web\jian24-web-platform\node_modules\mqtt\lib\client.js Unexpected token (118:38)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (118:38)
    at Parser.pp$4.raise (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseIdent (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:2189:12)
    at Parser.pp$3.parsePropertyName (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:2052:101)
    at Parser.pp$3.parseObj (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1988:14)
    at Parser.pp$3.parseExprAtom (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1805:19)
    at Parser.pp$3.parseExprSubscripts (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseMaybeAssign (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1608:25)
    at Parser.pp$3.parseExpression (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseBlock (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (D:\web\jian24-web-platform\node_modules\acorn\dist\acorn.js:709:33)
 @ ./~/mqtt/lib/connect/index.js 3:19-39`

**Comment by vishnureddy17** [comment]
Hi @shenhaoguangDayDayUp, what environment are you running this in? Browser? Node? Which version?

**Comment by YoDaMa** [comment]
closing due to inactivity.
