### ISSUE TITLE
If this is still an issue on the latest version please let me know and I'll reopen this.

### ISSUE THREAD

**Issue by acc8226** [mqttjs/MQTT.js#1464]
If this is still an issue on the latest version please let me know and I'll reopen this.

_Originally posted by @OmgImAlexis in https://github.com/mqttjs/MQTT.js/issues/821#issuecomment-626573602_

**Comment by acc8226** [comment]
when I run this command, it fails at the following line.

```
likai@DESKTOP-E15-001:~$ cat telemetry-data-as-object.json | mqtt pub -h "localhost" -t "v1/devices/me/telemetry" -u 'FgzAOYWnxXP5Qy2Lt3wT' -s
/usr/local/lib/node_modules/mqtt/bin/pub.js:121
  args.message = (args.message || args._.shift()).toString()
                                                  ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at Command.start [as func] (/usr/local/lib/node_modules/mqtt/bin/pub.js:121:51)
    at Command.call (/usr/local/lib/node_modules/mqtt/node_modules/commist/index.js:105:8)
    at Object.parse (/usr/local/lib/node_modules/mqtt/node_modules/commist/index.js:54:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mqtt/bin/mqtt.js:24:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

I have to pass a dummy message at the end of the command for this command to work.

```
likai@DESKTOP-E15-001:~$ cat telemetry-data-as-object.json | mqtt pub -h "localhost" -t "v1/devices/me/telemetry" -u 'FgzAOYWnxXP5Qy2Lt3wT' -s dummyMessage
```

my lamptop info:
sys: Ubuntu 20.04 LTS
MQTT.js version: 4.3.7
