### ISSUE TITLE
WebSocket connection to hivemq broker failed

### ISSUE THREAD

**Issue by Squirrelcoding** [mqttjs/MQTT.js#1500]
I am developing a NextJS web app for my project and I have this code:
```tsx
import { connect, AsyncMqttClient } from "async-mqtt";

const Page = () => {

let [client, setClient] = useState<AsyncMqttClient | null>(null);

useEffect(() => {
    if (client) {
        console.log(client);
        client.on("connect", () => {
            console.log("Reconnecting!");
        });
        client.on("error", (err) => {
            console.error("Connection error: ", err);
            client?.end();
        });
        client.on("reconnect", () => {
            console.log("Reconnecting!");
        });
        client.on("message", (topic, message) => {
            const payload = { topic, message: message.toString() };
            console.log(payload);
        });
    } else {
        setClient(connect("wss://<my hivemqt broker>", {
            username: "username",
            password: "password",
            clientId: "oeirfkgtjn",
            port: 8884,
            protocol: "wss",
            keepalive: 60,
            clean: true
        }));
    }
}, [client]);
    return (
        <>...</>
    );
};

```

I'm running a HiveMQ broker and I want to be able to subscribe to it and stuff but the thing is I'm only met with errors in the console:
```
ws.js?725c:109 WebSocket connection to 'ws://<my broker URL>:8884/' failed: 

createBrowserWebSocket @ ws.js?725c:109
browserStreamBuilder @ ws.js?725c:136
wrapper @ index.js?59e6:155
MqttClient._setupStream @ client.js?86b2:415
MqttClient._reconnect @ client.js?86b2:1105
eval @ client.js?86b2:1125
```

I connected to my broker using the [online WebSocket demo](https://websocketclient.hivemq.cloud/) and everything worked fine with providing the *exact same* information as the MQTT.js client. Does anybody have an idea of what the issue could be?

**Comment by Squirrelcoding** [comment]
oops i accidently submit the issue in the middle of writing this

**Comment by mottolini** [comment]
I have same problem, did you solve it?

In my case I used the CLI with the command:

    mqtt pub -t 'test/topic' -h 'mqtt.something.com' -p 8000 --protocol ws  -m '{"ws": "works"}'

And I got this log
```
  mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: options.protocol ws +0ms
  mqttjs:client MqttClient :: options.protocolVersion 4 +0ms
  mqttjs:client MqttClient :: options.username undefined +0ms
  mqttjs:client MqttClient :: options.keepalive 60 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized undefined +0ms
  mqttjs:client MqttClient :: options.topicAliasMaximum undefined +0ms
  mqttjs:client MqttClient :: clientId mqttjs_44ad2d85 +0ms
  mqttjs:client MqttClient :: setting up stream +1ms
  mqttjs:client _setupStream :: calling method to clear reconnect +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupStream :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for ws +2ms
  mqttjs:ws streamBuilder +0ms
  mqttjs:ws createWebSocket +1ms
  mqttjs:ws protocol: MQTT 4 +0ms
  mqttjs:ws creating new Websocket for url: ws://mqtt.something.com:8000/ and protocol: mqtt +0ms
  mqttjs:client _setupStream :: pipe stream to writable stream +5ms
  mqttjs:client _setupStream: sending packet `connect` +3ms
  mqttjs:client sendPacket :: packet: { cmd: 'connect' } +1ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +20ms
  mqttjs:client streamErrorHandler :: error socket hang up +10s
  mqttjs:client streamErrorHandler :: emitting error +0ms
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}
  mqttjs:client end :: (mqttjs_44ad2d85) +1ms
  mqttjs:client end :: cb? true +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client end :: (mqttjs_44ad2d85) :: immediately calling finish +0ms
  mqttjs:client end :: (mqttjs_44ad2d85) :: finish :: calling _cleanUp with force false +1ms
  mqttjs:client _cleanUp :: done callback provided for on stream close +0ms
  mqttjs:client _cleanUp :: forced? false +0ms
  mqttjs:client _cleanUp :: (mqttjs_44ad2d85) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_44ad2d85) ::  start +0ms
  mqttjs:client _sendPacket :: client not connected. Storing packet offline. +0ms
  mqttjs:client _storePacket :: packet: { cmd: 'disconnect' } +0ms
  mqttjs:client _storePacket :: cb? true +0ms
  mqttjs:client _cleanUp :: (mqttjs_44ad2d85) :: removing stream `done` callback `close` listener +0ms
  mqttjs:client end :: finish :: calling process.nextTick on closeStores +1ms
  mqttjs:client (mqttjs_44ad2d85)stream :: on close +0ms
  mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +0ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
  mqttjs:client end :: closeStores: closing incoming and outgoing stores +0ms
  mqttjs:client end :: closeStores: emitting end +1ms
  mqttjs:client end :: closeStores: invoking callback with args +0ms
  mqttjs:client nop :: undefined +0ms
```

The HiveMQ broker received the message but discarded it because of "pipeline configuration":
```
2022-10-15 13:55:03,664 TRACE - Discarded inbound message HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET / HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: kxs6/WuBmulA4lKBxakcLw==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: mqtt
Host: mqtt-eligo.omnixell.com:8000
content-length: 0 that reached at the tail of the pipeline. Please check your pipeline configuration.
2022-10-15 13:55:03,665 TRACE - Discarded message pipeline : [http_server_codec, http_object_aggregator, io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler, io.netty.handler.codec.http.websocketx.Utf8FrameValidator, websocket_server_protocol_handler, websocket_binary_frame_handler, websocket_text_frame_handler, mqtt_websocket_encoder, websocket_continuation_frame_handler, mqtt_message_decoder, mqtt_message_encoder, new_connection_idle_handler, no_connect_idle_event_handler, mqtt_message_barrier, plugin_initializer_handler, interceptor_handler, message_expiry_handler, mqtt_subscribe_handler, mqtt_publish_flush, client_lifecycle_event_handler, mqtt_auth_handler, mqtt_connect_handler, mqtt_pingreq_handler, mqtt_unsubscribe_handler, mqtt_disconnect_handler, exception_handler, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0xecfdeced, L:/172.22.0.2:8000 - R:/151.14.59.45:52533].
2022-10-15 13:55:11,238 TRACE - PingReq received for client mqttjs_0d70b87b.
2022-10-15 13:55:11,238 TRACE - PingResp sent for client mqttjs_0d70b87b.
2022-10-15 13:55:13,665 DEBUG - Client with IP 151.14.59.45 disconnected. The client was idle for too long without sending a MQTT CONNECT packet.
2022-10-15 13:55:13,666 TRACE - Client null was disconnected.
```

**Comment by mottolini** [comment]
In my case the problem was that HIveMQ awaits websocket traffic by default at path /mqtt, while the mqtt CLI tool doesn't support a path. So, HiveMQ was awaiting on `ws://mqtt.something.com:8000/mqtt` while the mqtt CLI Tool was using `ws://mqtt.something.com:8000/mqtt`. It shouldn't be difficult to add support for a `--path` option (hopefully someone could create a PR for it).

I solved it on my side changing the configuration of HiveMQ broker with the following `config.xml` file:
```xml
```xml
<?xml version="1.0"?>
<hivemq>
    <listeners>
        <tcp-listener>
            <port>1883</port>
            <bind-address>0.0.0.0</bind-address>
        </tcp-listener>
        <websocket-listener>
            <port>8000</port>
            <bind-address>0.0.0.0</bind-address>
            <path>/</path>
            <name>my-websocket-listener</name>
            <subprotocols>
                <subprotocol>mqttv3.1</subprotocol>
                <subprotocol>mqtt</subprotocol>
            </subprotocols>
            <allow-extensions>true</allow-extensions>
        </websocket-listener>
    </listeners>
</hivemq>
```

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists

Also consider try connecting using `wss://` instead of `ws://`
