### ISSUE TITLE
Crash with Error: WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by jsiegenthaler** [mqttjs/MQTT.js#1550]
On MQTT 4.3.7, running on Node 18.12.0, following a failed connection on a Mac Mini, this results in a crash with
mqttjs:client streamErrorHandler :: error WebSocket was closed before the connection was established

The websocket closure should be made more robust to prevent closure attempts before a connection is established.

Log snippet follows:

2022-11-10T16:21:57.874Z mqttjs:client _setupReconnect :: doing nothing...
2022-11-10T16:21:58.875Z mqttjs:client reconnectTimer :: reconnect triggered!
2022-11-10T16:21:58.877Z mqttjs:client _reconnect: emitting reconnect to client
2022-11-10T16:21:58.877Z mqttjs:client _reconnect: calling _setupStream
2022-11-10T16:21:58.877Z mqttjs:client _setupStream :: calling method to clear reconnect
2022-11-10T16:21:58.877Z mqttjs:client _clearReconnect : clearing reconnect timer
2022-11-10T16:21:58.877Z mqttjs:client _setupStream :: using streamBuilder provided to client to create stream
2022-11-10T16:21:58.877Z mqttjs calling streambuilder for wss
2022-11-10T16:21:58.877Z mqttjs:ws streamBuilder
2022-11-10T16:21:58.877Z mqttjs:ws createWebSocket
2022-11-10T16:21:58.877Z mqttjs:ws protocol: MQTT 4
2022-11-10T16:21:58.878Z mqttjs:ws creating new Websocket for url: wss://obomsg.prod.ch.horizon.tv:443/mqtt and protocol: mqtt
2022-11-10T16:21:58.889Z mqttjs:client _setupStream :: pipe stream to writable stream
2022-11-10T16:21:58.889Z mqttjs:client _setupStream: sending packet `connect`
2022-11-10T16:21:58.891Z mqttjs:client sendPacket :: packet: { cmd: 'connect' }
2022-11-10T16:21:58.891Z mqttjs:client sendPacket :: emitting `packetsend`
2022-11-10T16:21:58.891Z mqttjs:client sendPacket :: writing to stream
2022-11-10T16:21:58.891Z mqttjs:client sendPacket :: writeToStream result true
2022-11-10T16:22:08.894Z mqttjs:client !!connectTimeout hit!! Calling _cleanUp with force `true`
2022-11-10T16:22:08.894Z mqttjs:client _cleanUp :: forced? true
2022-11-10T16:22:08.894Z mqttjs:client _cleanUp :: (ljg4yomi-ypkq-y5ad-twir-8lyt9qq32q0d) :: destroying stream
2022-11-10T16:22:08.896Z mqttjs:client _cleanUp :: client not disconnecting. Clearing and resetting reconnect.
2022-11-10T16:22:08.896Z mqttjs:client _clearReconnect : clearing reconnect timer
2022-11-10T16:22:08.896Z mqttjs:client _setupReconnect :: setting reconnectTimer for 1000 ms
2022-11-10T16:22:08.896Z mqttjs:client streamErrorHandler :: error WebSocket was closed before the connection was established
2022-11-10T16:22:08.896Z mqttjs:client nop :: Error: WebSocket was closed before the connection was established
    at WebSocket.terminate (/usr/local/lib/node_modules/homebridge-eosstb/node_modules/ws/lib/websocket.js:433:14)
    at Duplex.duplex._destroy (/usr/local/lib/node_modules/homebridge-eosstb/node_modules/ws/lib/stream.js:123:32)
    at _destroy (node:internal/streams/destroy:109:10)
    at Duplex.destroy (node:internal/streams/destroy:71:5)
    at MqttClient._cleanUp (/usr/local/lib/node_modules/homebridge-eosstb/node_modules/mqtt/lib/client.js:1160:17)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eosstb/node_modules/mqtt/lib/client.js:518:10)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
2022-11-10T16:22:08.897Z mqttjs:client (ljg4yomi-ypkq-y5ad-twir-8lyt9qq32q0d)stream :: on close
2022-11-10T16:22:08.897Z mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function
2022-11-10T16:22:08.897Z mqttjs:client stream: emit close to MqttClient
2022-11-10T16:22:08.897Z mqttjs:client close :: connected set to `false`
2022-11-10T16:22:08.897Z mqttjs:client close :: clearing connackTimer
2022-11-10T16:22:08.897Z mqttjs:client close :: clearing ping timer
2022-11-10T16:22:08.897Z mqttjs:client close :: calling _setupReconnect
2022-11-10T16:22:08.897Z mqttjs:client _setupReconnect :: doing nothing...

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
