### ISSUE TITLE
process.nextTick is not a function

### ISSUE THREAD

**Issue by 55764418** [mqttjs/MQTT.js#1653]
_stream_readable.js:832 Uncaught (in promise) TypeError: process.nextTick is not a function
    at resume (_stream_readable.js:832:13)
    at Readable.resume (_stream_readable.js:824:5)
    at Readable.on (_stream_readable.js:753:39)
    at Readable.pipe (_stream_readable.js:626:7)
    at MqttClient.connect (client.ts:764:15)
    at new MqttClient (client.ts:656:9)
    at connect (index.ts:173:17)
    at conn (mqtt.ts:18:12)
    at ImportDetail.vue:55:3
    at runtime-core.esm-bundler.js:2675:88

This error is reported using mqtt.
My environment:
vue 3.3.4 + vite 4.3.9

**Comment by robertsLando** [comment]
See https://github.com/mqttjs/MQTT.js/issues/1639#issuecomment-1659996292
