### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by guptaashwanee** [mqttjs/MQTT.js#1701]
I have tried "mqtt": "^5.0.0-beta.0", also "mqtt": "^4.x.x", still no success.
I have also used the solution to use in webpack5 about polyfill, also builded through webpack

## This is the browser log that I got,

ERROR
process is not defined
ReferenceError: process is not defined
    at ./node_modules/mqtt/lib/client.js (http://localhost:3000/static/js/bundle.js:17763:18)
    at options.factory (http://localhost:3000/static/js/bundle.js:73496:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:72919:33)
    at fn (http://localhost:3000/static/js/bundle.js:73153:21)
    at ./node_modules/mqtt/lib/connect/index.js (http://localhost:3000/static/js/bundle.js:19681:20)
    at options.factory (http://localhost:3000/static/js/bundle.js:73496:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:72919:33)
    at fn (http://localhost:3000/static/js/bundle.js:73153:21)
    at ./src/hooks/useMQTT.js (http://localhost:3000/static/js/bundle.js:379:62)
    at options.factory (http://localhost:3000/static/js/bundle.js:73496:31)

## package.json dependencies:

"dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "mqtt": "^5.0.0-beta.0",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "process": "^0.11.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "url": "^0.11.3",
    "web-vitals": "^2.1.4"
  },

Is there any key that I am missing.

**Comment by robertsLando** [comment]
Use mqtt latest version 5.0.7 and import mqtt like this in browser:

```js
import * as mqtt from 'mqtt/dist/mqtt.min'
```

**Comment by wecall1** [comment]
Thanks for the tip @robertsLando but then there are no types :/ in vscode

**Comment by wildfluss** [comment]
Thanks for the tip [@robertsLando](https://github.com/robertsLando) but then there are no types :/ in vscode

**Comment by robertsLando** [comment]
Check https://github.com/mqttjs/MQTT.js/issues/1729

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
