### ISSUE TITLE
[Bug]: Error: Invalid header flag bits, must be 0x0 for puback packet

### ISSUE THREAD

**Issue by geek3000** [mqttjs/MQTT.js#1790]
### MQTTjs Version

5.3.5

### Broker

Emqx

### Environment

NodeJS

### Description

I get this error when I try to connect to my broker with the mqtt.js library.

My broker has been deployed in a kubernetes cluster and it is exposed via an Nginx ingress

Here is the command:

`mqtt pub -t '/testtopic' -h 'broker_host' -p 443 -m 'from' `

### Minimal Reproduction

1. Install mqtt.js 
`npm install -g mqtt`

2. Execute the command
`mqtt pub -t '/testtopic' -h 'broker_host' -p 443 -m 'from'`

### Debug logs

```
Error: Invalid header flag bits, must be 0x0 for puback packet
    at Parser._parseHeader (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\node_modules\mqtt-packet\parser.js:63:30)       
    at Parser.parse (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\node_modules\mqtt-packet\parser.js:43:45)
    at writable._write (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\build\lib\client.js:240:20)
    at writeOrBuffer (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\node_modules\readable-stream\lib\internal\streams\writable.js:334:12)
    at _write (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\node_modules\readable-stream\lib\internal\streams\writable.js:283:10)
    at Writable.write (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\mqtt\node_modules\readable-stream\lib\internal\streams\writable.js:286:10)
    at Socket.ondata (node:internal/streams/readable:1007:22)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
```

**Comment by yaraiw** [comment]
Have you resolved the issue ? what was the problem?

**Comment by yaraiw** [comment]
I have faced the same issue

**Comment by davidCcD** [comment]
Have you resolved the issue ? what was the problem? I have faced the same issue.

**MQTTjs Version**
mqtt 5.10.1

**Broker**
aedes 0.51.3

**Environment**
NodeJS 20.9.0

**Description**
I get this error when I try to connect to my broker with the mqtt.js library in Vue via Chrome.

My broker can be connected succuessfully via App such MQTTX with mqtt://... , but failed via web browser with ws://....

**Minimal Reproduction**

_NodeJs side, code:_
aedes.on('connectionError', function (client, error) {
    console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' connectionError' + error.toString());
});

_VueJs side, code:_
const connection = {
  protocol: "ws",
  protocolId: 'MQTT',
  protocolVersion:4,
  // protocolId: 'MQIsdp',
  // protocolVersion: 3,
  host: "192.168.1.6",
  port: 8083,
  endpoint:"/mqtt",
  clientId: "vue3_" + Math.random().toString(16).substring(2, 8),
  username: "username",
  password: "password",
  clean: true,
  connectTimeout: 3000,
  reconnectPeriod: 4000,
  // forceNativeWebSocket:true
  // for more options and details, please refer to https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options
};

**Debug logs**

_NodeJs side, emitted this log:_
null connectionError Error: Invalid header flag bits, must be 0x0 for puback packet

_Chrome side, log:_
WebSocket connection to 'ws://192.168.1.6:8083/mqtt' failed: 
aS @ mqtt.js?v=1422640a:11542
uS @ mqtt.js?v=1422640a:11556
s @ mqtt.js?v=1422640a:11832
connect @ mqtt.js?v=1422640a:9852
_reconnect @ mqtt.js?v=1422640a:10079
(anonymous) @ mqtt.js?v=1422640a:10083

**Comment by davidCcD** [comment]
Today I find it should be a bug in my aedes.js broker, not matt.js, because I changed host as below and connected successfully.
 // host:"192.168.1.6", // <-- this is my aedes.js broker
 host:"broker.emqx.io", // <-- this is a free public broker for test
