### ISSUE TITLE
[Bug]: Error "Missing protocol" when running demo code in README

### ISSUE THREAD

**Issue by 3DRX** [mqttjs/MQTT.js#1804]
### MQTTjs Version

5.3.6

### Broker

mosquitto

### Environment

NodeJS

### Description

This code segment in README
```js
const mqtt = require("mqtt")  // require mqtt
const client = mqtt.connect("test.mosquitto.org")  // create a client
```
can cause following error

Error: Missing protocol

### Minimal Reproduction

execute this code segment

### Debug logs

            throw new Error('Missing protocol');
            ^

Error: Missing protocol
    at Object.connect (/home/kjy/Documents/projects/wl-cloudgame-data/src/utils/gs-data-collector/node_modules/mqtt/build/lib/connect/index.js:55:19)
    at Object.<anonymous> (/home/kjy/Documents/projects/wl-cloudgame-data/src/utils/gs-data-collector/test.cjs:2:21)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0

**Comment by 3DRX** [comment]
#1805
