### ISSUE TITLE
Cannot use Chinese topic

### ISSUE THREAD

**Issue by duyaokun** [mqttjs/MQTT.js#200]
If use Chinese topic,the exception throw:
buffer.js:788
    throw RangeError('Trying to write outside buffer length');
          ^
RangeError: Trying to write outside buffer length
    at RangeError (<anonymous>)
    at checkInt (buffer.js:788:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at Object.eval [as writeUInt8](eval at <anonymous> %28mqtttestnode_modulesmqttnode_modulesbopswrite.js:11:10%29, <anonymous>:2:12)
    at Object.module.exports.subscribe (\mqtttest\node_modules\mqtt\lib\generate.js:336:10)
    at Connection.eval [as subscribe](eval at <anonymous> %28mqtttestnode_modulesmqttlibconnection.js:58:29%29, <anonymous>:2:26)
    at MqttClient._sendPacket (\cloud\mqtttest\node_modules\mqtt\lib\client.js:438:20)
    at MqttClient.<anonymous> (\mqtttest\node_modules\mqtt\lib\client.js:105:12)
    at MqttClient.EventEmitter.emit (events.js:117:20)
    at MqttClient._handleConnack (\mqtttest\node_modules\mqtt\lib\client.js:506:10)

My Code is:
var client = require('mqtt').createClient();
client.publish('中国', 'hello!');
client.subscribe('中国');
client.on('message', function(topic, message) {
console.log(message);
});
client.end();

**Comment by bo-bo2016** [comment]
Good job！！！

**Comment by sublimator** [comment]
Uhm wat?
