### ISSUE TITLE
Missing Packet publishing with QoS 2

### ISSUE THREAD

**Issue by xadh00m** [mqttjs/MQTT.js#344]
Hi,

I´ve made a NodeJS project with MQTT.js 1.5.0 which publishes to a topic 10 times per second to a local HiveMQ 2.3.1 for testing. I always get the following error after usually less then 100 messages published:

```
Error: missing packet
    at Store.get (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/lib/store.js:94:8)
    at MqttClient._handlePubrel (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/lib/client.js:833:22)
    at MqttClient._handlePacket (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/lib/client.js:271:12)
    at process (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/lib/client.js:218:12)
    at Writable.writable._write (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/lib/client.js:228:5)
    at doWrite (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/dev/projects/focus/debug-topic-publisher/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```
It seems that the packet has been removed from store already. Is this a known issue? Any hints on how I could approach/fix this error?

Regards,
Mirko

**Comment by mcollina** [comment]
There are a couple of options in the MQTT spec regarding how messages are stored for QoS 2. Maybe the way it is implemented here is not working well with HiveMQ.

Have you checked with Mosquitto as well?

Probably the best way to fix this is to add some `console.log` where things are deleted: https://github.com/mqttjs/MQTT.js/blob/master/lib/store.js#L72

**Comment by jdiamond** [comment]
I tried reproducing this using the [public HiveMQ test broker](http://www.hivemq.com/try-out/) with the following script:

```
#!/usr/bin/env node

var mqtt = require('mqtt');

var client = mqtt.connect('mqtt://broker.hivemq.com');

client.on('connect', function() {
    var count = 0;

    (function publish() {
        client.publish('foo', 'bar', { qos: 2 }, function() {
            count++;

            if (count % 100 === 0) {
                console.log('published %d messages', count);
            }

            publish();
        });
    })();
});
```

It published a 1000 messages without errors before I stopped it.

This broker seems verrry slow. I imagine it's either throttled because it's only for testing or it's overloaded because it's public and being abused.

If this is still an issue for you and you have more information to help us reproduce it, feel free to reopen.

**Comment by parveen-oodles** [comment]
Hello jdiamond ,
I am also getting the missing packet exception. I am using mosquitto and node module mqtt for chatting purpose but sometime i am getting the exception that is ** missing packet **. I am not able to debug from where and when this error occurred , we have setup mosquitto broker on ubuntu machine and client side we are using android  so some times i got this error in server and server is getting very slow and after that it will take so much time to made connection and also it will connect and disconnect some time , so please let me know where i am wrong and how should i debug this thing.
