### ISSUE TITLE
mqtt_sub throws exception

### ISSUE THREAD

**Issue by ecksun** [mqttjs/MQTT.js#411]
After installing mqtt in a project I tried to use the mqtt_sub client:

    ./node_modules/.bin/mqtt_sub --verbose --topic #

However this throws a TypeError:

```

/home/user/code/m/node_modules/mqtt/lib/client.js:423
      .keys(obj)
       ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at MqttClient.subscribe (/home/user/code/m/node_modules/mqtt/lib/client.js:423:8)
    at MqttClient.<anonymous> (/home/user/code/m/node_modules/mqtt/bin/sub.js:92:12)
    at MqttClient.emit (events.js:117:20)
    at MqttClient._handleConnack (/home/user/code/m/node_modules/mqtt/lib/client.js:705:10)
    at MqttClient._handlePacket (/home/user/code/m/node_modules/mqtt/lib/client.js:286:12)
    at process (/home/user/code/m/node_modules/mqtt/lib/client.js:230:12)
    at Writable.writable._write (/home/user/code/m/node_modules/mqtt/lib/client.js:240:5)
    at doWrite (/home/user/code/m/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/user/code/m/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)

```

I don't know if Im using the client incorrectly, but even if I am I would expect an error-message that explains what I'm doing wrong.

**Comment by mcollina** [comment]
I think you are not passing any topic, because `#` is interpreted as a comment in bash.
The real bug is the lack of a decent error message.. would you like to send a PR?

Thanks!

**Comment by ecksun** [comment]
Oh my, how could I have missed that.

Yes indeed, the error-message needs to be improved, I will try to get some time to create a PR
