### ISSUE TITLE
Error: missing packet

### ISSUE THREAD

**Issue by shylesh107** [mqttjs/MQTT.js#415]
Hi,

I'm getting this error

```
Error: missing packet
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: missing packet
    at Store.get (/src/node_modules/mqtt/lib/store.js:92:8)
    at MqttClient._handlePubrel (/src/node_modules/mqtt/lib/client.js:868:22)
```

Looking at the mosquitto logs it's happening when the broker sends the retained qos2 messages to client.

```
1464891913: New client connected from 141.117.xx.xx as Message_Manager (c0, k10).
1464891913: Sending CONNACK to Message_Manager (1, 0)
1464891913: Sending PUBREL to Message_Manager (Mid: 244)
1464891913: Sending PUBREL to Message_Manager (Mid: 245)
1464891913: Sending PUBREL to Message_Manager (Mid: 246)
1464891913: Sending PUBLISH to Message_Manager (d1, q2, r0, m249, 'q/chat/1011/message', ... (12 bytes))
1464891913: Sending PUBLISH to Message_Manager (d1, q2, r0, m250, 'q/chat/1011/message', ... (12 bytes))
1464891913: Sending PUBLISH to Message_Manager (d1, q2, r0, m267, 'q/chat/1011/message', ... (12 bytes))
1464891913: Sending PUBLISH to Message_Manager (d1, q2, r0, m268, 'q/chat/1011/message', ... (12 bytes))
1464891913: Socket error on client Message_Manager, disconnecting.
```

This is my connection configuration : 

``` js
    MQTTClient = mqtt.connect(MQTT_BROKER,
        {
            clientId: MQTT_SERVER_ID,
            clean: false // To receive QoS 1 and 2 messages while offline
        });
```

The client is crashing every time I try to run it. The only fix that seems to be working it setting the clean flag to false and changing the ClientID (thus creating a new session)

This is the portion of lib code that's throwing the error.

``` js
packet = this._inflights[packet.messageId];
```

I console logged the this._inflights and it's an empty {}

Any help will be appreciated.

**Comment by mcollina** [comment]
You are right, the logic needs to be changed so that it does not error when getting unknown message ids. Would you (or someone else) like to send a PR?

**Comment by shylesh107** [comment]
I will take a look when I get some time. Thank you.

**Comment by shylesh107** [comment]
#416 This seems to have solved my issue. Tested it with mosquitto receiving  QoS 2 messages.
