### ISSUE TITLE
TypeError: Argument must be a string

### ISSUE THREAD

**Issue by priyanka8929** [mqttjs/MQTT.js#449]
Hi,

I am using aws-iot-sdk in NodeJS which uses MQTTS protocol. I am getting the following error repeatedly at random times during the day. _NOTE: The device is using a cellular connection(AT&T)_

I tried debugging it and got the following stack trace for the error. It looks like it's happening when **drainOperationQueue()** tries to publish a message after connection has been established. I am not able to find out why this happens.

**TypeError: Argument must be a string
at DeviceClient.<anonymous> (/usr/local/src/armhf-vvo-iot/iot_device_test.js:203:11)
at emitOne (events.js:77:13)
at DeviceClient.emit (events.js:169:7)
at MqttClient.<anonymous> (/usr/local/src/armhf-vvo-iot/node_modules/aws-iot-device-sdk/device/index.js:655:12)
at emitOne (events.js:77:13)
at MqttClient.emit (events.js:169:7)
at sendPacket (/usr/local/src/armhf-vvo-iot/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:44:14)
at MqttClient._sendPacket (/usr/local/src/armhf-vvo-iot/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:620:7)
at MqttClient.publish (/usr/local/src/armhf-vvo-iot/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:364:12)
at _drainOperationQueue \[as _repeat\] (/usr/local/src/armhf-vvo-iot/node_modules/aws-iot-device-sdk/device/index.js:575:26)**

Any help would be appreciated!

Thanks!

**Comment by RangerMauve** [comment]
Can we see what's around line 203 in `iot_device_test.js`?

**Comment by priyanka8929** [comment]
@RangerMauve 

I found the problem. I was trying to publish the error object, instead of error.message at line 203. 

Thanks for looking into it!!
