### ISSUE TITLE
Missing secure protocol key

### ISSUE THREAD

**Issue by arunbangari** [mqttjs/MQTT.js#474]
Hi,
When I run the mqttclient.js in the tls client example, I get the following error
# node mqttclient.js
/root/node_modules/mqtt/lib/connect/index.js:103
      throw new Error('Missing secure protocol key')
      ^

Error: Missing secure protocol key
    at Object.connect (/root/node_modules/mqtt/lib/connect/index.js:103:13)
    at Object.<anonymous> (/root/node_modules/mqtt/examples/tls client/mqttclient.js:39:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
 
I was trying to modify the mqttclient.js to connect to mqtt broker over tls which is running on raspberry pi. But I got the same error. Then I tried the mqttclient in example and I get the same error.  Any help or pointers greatly appreciated.

Br,Arun

**Comment by arunbangari** [comment]
Solved. As mentioned in one of the comments in #339 specifying mqtts://host in connect solves the problem. Thanks!
