### ISSUE TITLE
random Cannot read property "forEach" of undefined

### ISSUE THREAD

**Issue by djflex68** [mqttjs/MQTT.js#506]
Hello,

I'm getting the following error randomly while listening to event messages :

> (...)\dist\node_modules\mqtt\lib\client.js:465
>       subs.forEach(function (sub) {
>           ^
> 
> TypeError: Cannot read property 'forEach' of undefined
>     at MqttClient.subscribe.outgoing.(anonymous function) ...\mqtt\lib\client.js:465:11)
>     at __dirname.MqttClient.options.on.outStore.once.that.outgoing.(anonymous function) (...\dist\node_modules\mqtt\lib\client.js:140:15)
>     at (...)\dist\node_modules\mqtt\lib\client.js:881:9
>     at Store.del ((...)\dist\node_modules\mqtt\lib\store.js:77
> :5)
>     at MqttClient._handleAck ((...)\dist\node_modules\mqtt\lib
> \client.js:868:26)
>     at MqttClient._handlePacket ((...)\dist\node_modules\mqtt\
> lib\client.js:293:12)
>     at process ((...)\dist\node_modules\mqtt\lib\client.js:242
> :12)
>     at Writable.MqttClient._setupStream.writable._write ((...)
> \dist\node_modules\mqtt\lib\client.js:252:5)
>     at doWrite ((...)\dist\node_modules\readable-stream\lib\_s
> tream_writable.js:319:64)
>     at writeOrBuffer ((...)\dist\node_modules\readable-stream\
> lib\_stream_writable.js:308:5)
>     at Writable.write ((...)\dist\node_modules\readable-stream
> \lib\_stream_writable.js:246:11)
>     at Socket.ondata (_stream_readable.js:536:20)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at Socket.Readable.push (_stream_readable.js:111:10)
> 

What could be going on ? 

My code :

 ```
const replyTopic = [
            "foo/device/+/reply/+" // subscribe to device management (add/remove/update)
        ];
        replyTopic.forEach((topic) => {
            this.mqttClient.subscribe(replyTopic);
        });

 var self = this;
 this.mqttClient.on('message', (topic: string, message: any) => {
            self.onMessageReceived(topic, message);
        });

 public sendRequest(topic: string, message: any): Promise<any> {
     var id = this.generateUUID();
        // topic should always have the form something/.../id for the request
        // and something/.../reply/id for the answer
        var topic = topic.replace("{id}", id);
        try {
            (...)
            this.mqttClient.publish(topic, JSON.stringify(message));
            (...)
       } catch (...)
}
 private onMessageReceived(topic: string, message: any) : void { ... }
```

**Comment by mcollina** [comment]
can you please send a full node.js example?

**Comment by djflex68** [comment]
After logging all events (connect, reconnect, close, offline), I noticed that I have a loop : connected -> offline -> recconect. I cannot figure out what is not working correctly.

Both problems could be linked. My code is currently in Typescript,  I will convert it to javascript for you if you want.

**Comment by mcollina** [comment]
@djflex68 please do, and provide a full example that reproduces the issue reliably. Thanks!

**Comment by djflex68** [comment]
This is the class I'm using (converted from Typescript to javascript) for managing my mqtt requests.
```

define(["require", "exports", 'bluebird', "mqtt", "model/enums", "core/parameters"], function (require, exports, bluebird_1, mqtt, enums_1, parameters_1) {
    "use strict";
    // Class
    var XLRequestBuilder = (function () {
        function XLRequestBuilder() {
            var _this = this;
            this.promiseMap = {};
            var self = this; // needed to keep context (because mqtt client changes "this" context even in the lambda expression)
            this.mqttClient = mqtt.connect(parameters_1.Parameters.MQTT_SERVER, { clientId: parameters_1.Parameters.MQTT_CLIENTID, username: parameters_1.Parameters.MQTT_USERNAME, password: parameters_1.Parameters.MQTT_PASSWORD });
            this.mqttClient.on("error", function (error) {
                console.warn("MQTT client error : " + error);
            });
            this.mqttClient.on("offline", function (error) {
                console.warn("MQTT client went offline !");
            });
            this.mqttClient.on("close", function (error) {
                console.warn("MQTT closed unexpectedly !");
            });
            this.mqttClient.on("reconnect", function (error) {
                console.warn("MQTT reconnected unexpectedly !");
            });
            this.isConnected = new bluebird_1.Promise(function (resolve, reject) {
                self.mqttClient.on("connect", function (connack) {
                    console.warn("MQTT client connected. " + connack);
                    self.subscribeToReplyTopics();
                    resolve(true);
                });
            });
            this.timeoutRequestId = setInterval(function () { _this.checkTimeoutRequest(); }, 1000);
            this.timeout = parseInt(parameters_1.Parameters.MQTT_TIMEOUT) || 10;
            this.mqttClient.on('message', function (topic, message) {
                self.onMessageReceived(topic, message);
            });
        }
        XLRequestBuilder.prototype.subscribeToReplyTopics = function () {
            var _this = this;
            var replyTopic = [
                "myapp/device/+/reply/+" // subscribe to device management (add/remove/update)
            ];
            replyTopic.forEach(function (topic) {
                _this.mqttClient.subscribe(replyTopic);
            });
        };
        XLRequestBuilder.prototype.onMessageReceived = function (topic, message) {
            var topicParts = topic.split("/");
            var id = topicParts[topicParts.length - 1];
            var result = JSON.parse(message.toString());
            if (!this.promiseMap[id]) {
                console.warn("There is no promise declared for the id " + id);
            }
            else {
                // the id must match the same request topic
                if (this.promiseMap[id].expectedReplyTopic === topic) {
                    var result = JSON.parse(message.toString());
                    if (result.result && result.result.success) {
                        this.promiseMap[id].promise.resolve(result);
                        delete this.promiseMap[id];
                    }
                    else {
                        this.promiseMap[id].promise.reject({ code: enums_1.ErrorCode.MqttRemoteError, errorLabel: result.result.errorCode });
                        delete this.promiseMap[id];
                    }
                }
                else {
                    delete this.promiseMap[id]; // delete it
                }
            }
        };
        XLRequestBuilder.prototype.checkTimeoutRequest = function () {
            var now = new Date();
            for (var key in this.promiseMap) {
                if ((now.getTime() - this.promiseMap[key].timestamp.getTime()) > this.timeout * 1000) {
                    // Reject the given promie
                    this.promiseMap[key].promise.reject({ code: enums_1.ErrorCode.MqttRequestTimeout, errorLabel: "ETIMEOUT" });
                    delete this.promiseMap[key];
                }
            }
        };
        /**
        *
        *    Send MQTT message
        *
        *    @param    {string}    topic    the URL
        *    @param    {string}    message The message to send
        *
        *    @returns    {Array.<module:D64.Promise<any>>}    An array of all sent MQTT Promises
        *
        *    @memberof    module:D64.Services.DataProvider.EndPoints.RequestBuilder#
        *    @method    buildAndSendRequests
        */
        XLRequestBuilder.prototype.sendRequest = function (topic, message) {
            var _this = this;
            return this.isConnected.then(function () {
                var id = _this.generateUUID();
                // topic should always have the form something/.../id for the request
                // and something/.../reply/id for the answer
                var topic = topic.replace("{id}", id);
                try {
                    var replyTopicParts = topic.split("/");
                    replyTopicParts.splice(replyTopicParts.length - 1, 0, "reply");
                    var expectedReplyTopic = replyTopicParts.join("/");
                    _this.mqttClient.publish(topic, JSON.stringify(message), { qos: 0 }, function (err) {
                        if (err) {
                            console.log("MQTT publish error : " + err);
                        }
                    });
                    _this.promiseMap[id] = {
                        promise: _this.getDeferred(),
                        timestamp: new Date(),
                        expectedReplyTopic: expectedReplyTopic // allow filtering the right messages later
                    };
                    return _this.promiseMap[id].promise.promise;
                }
                catch (e) {
                    return bluebird_1.Promise.reject(e.message);
                }
            });
        };
        XLRequestBuilder.prototype.generateUUID = function () {
            var d = new Date().getTime();
            var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                var r = (d + Math.random() * 16) % 16 | 0;
                d = Math.floor(d / 16);
                return (c == 'x' ? r : (r & 0x3 | 0x8)).toString(16);
            });
            return uuid;
        };
        ;
        XLRequestBuilder.prototype.getDeferred = function () {
            var result = {
                promise: null,
                resolve: null,
                reject: null
            };
            result.promise = new bluebird_1.Promise(function (resolve, reject) {
                result.reject = reject;
                result.resolve = resolve;
            });
            return result;
        };
        return XLRequestBuilder;
    }());
    exports.XLRequestBuilder = XLRequestBuilder;
});

```

My parameters : 
  "mqtt.server": "mqtt://xxx.xxx.xx.xxx",
  "mqtt.clientId": "foo",
  "mqtt.username": "bar",
  "mqtt.password": "bar",
  "mqtt.timeout": "30"

**Comment by mcollina** [comment]
how do I run/use your code? Can you provide an example that I can run to reproduce your error?

**Comment by djflex68** [comment]
Ok I figured out what was causing this problem.
We use the same clientId in our team from several IP address. I think the broker was not very happy with that and was rejecting me, causing the connect/disconnect loop. This might explain my initial error.
For now I'll be using default random clientId mechanism.
Thanks for your support !
