### ISSUE TITLE
Iterating through multiple events

### ISSUE THREAD

**Issue by TinMarkovic** [mqttjs/MQTT.js#553]
Upon executing the snippet (other code is cleaned up, as I've wanted to narrow it down):

```
var event_list = payload.data;

for(let event of event_list){
  client.publish(event.name, event.body);
}
```

I get the error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Function.app.listen (/home/tin/Projects/ExtensionEngine/mqtt-node-api/node_modules/express/lib/application.js:531:24)
    at MqttClient.<anonymous> (/home/tin/Projects/ExtensionEngine/mqtt-node-api/server.js:37:7)
    at emitOne (events.js:82:20)
    at MqttClient.emit (events.js:169:7)
    at MqttClient._handleConnack (/home/tin/Projects/ExtensionEngine/mqtt-node-api/node_modules/mqtt/lib/client.js:757:10)
```

Sending a single event functions properly, but trying to send events through an array does not. I've tried to emit them via callbacks, that didn't help either.

I have also made sure that nothing else is using that port.

Is there something wrong with my code, or a misunderstanding of the library, or is it a genuine issue?

**Comment by mcollina** [comment]
In your code, you are calling `server.listen()` at line 37 of /home/tin/Projects/ExtensionEngine/mqtt-node-api/server.js. It's in your code.
