### ISSUE TITLE
Can't connect to Server

### ISSUE THREAD

**Issue by davweiss** [mqttjs/MQTT.js#612]
Hello,

i trie since 3 Days to connect to the SAP MQTT over WSS (wss://iotmmsXXXXXXXXX.hana.ondemand.com/com.sap.iotservices.mms/v1/api/ws/mqtt).
With this i'm using a p12 client certificate.
But it goes to stuck on/ after the Handshake (see Wireshark Picture).
![wireshark](https://cloud.githubusercontent.com/assets/20642456/26107911/2d7a2664-3a4b-11e7-9c65-8689b1e32abe.png)
10.XX.XX.XXX is my IP
155.XX.XX.XXX is the SAP IP 

After 30 seconds i got this error:
![output](https://cloud.githubusercontent.com/assets/20642456/26107508/d0df65c8-3a49-11e7-854f-6739166c7f75.png)
And he try to connect again.

Here is the Source: 
```js
const fs = require('fs');
const mqtt = require('mqtt');

// Parts of URL and Path
const hcp_account_id = 'WWWWWWWWW';
const hcp_landscape_host = '.hana.ondemand.com' // this is used on PROD with Client Certificate Authentication
const my_endpoint_url_path = '/com.sap.iotservices.mms/v1/api/ws/mqtt';

//Certificate
const client_p12 = "./YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY.p12";

// the following values need to be taken from the IoT Cockpit
const device_id = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX';
const message_type_id_From_device = 'ZZZZZZZZZZZZZZZZZZZZ';

// for down- upstream communication
var my_publish_topic = "iot/data/" + device_id;
var my_subscription_topic = "iot/push/" + device_id;

var my_endpoint = "iotmms" + hcp_account_id + hcp_landscape_host;

var wsoptions =
    {
        host: my_endpoint,
        port: 443,
        pfx: fs.readFileSync(client_p12),
        passphrase: 'AAAAA',
        checkServerIdentity: false,
        protocol: 'mqttv3.1',
        protocolVersion: 13,
        perMessageDeflate: true,
        client_max_window_bits: true
    }

var options =
    {
        wsOptions: wsoptions,
        clientId: device_id,
        protocolId: 'MQIsdp',
        protocolVersion: 3,
        protocol: 'wss',
        hostname: my_endpoint,
        port: 443,
        path: my_endpoint_url_path
    }

const mqttc = mqtt.connect(options);

mqttc.subscribe(my_subscription_topic, 0);

mqttc.on('connect', () => console.log('connected!'));

mqttc.on('error', (msg) => console.log('error: ' + msg));

mqttc.on('offline', (msg) => console.log('offline: ' + msg));

mqttc.on('close', (msg) => console.log('close: ' + msg));

// message is Buffer
mqttc.on('message', (topic, message) => console.log('message(' + topic + '): ' + message.toString()));

```

**Comment by mcollina** [comment]
It's really hard to help you without a sap broker.
Have you tried running a debug session on your node client?
The best option is for you to contact their support.

**Comment by mcollina** [comment]
There seems to be a bug in your broker code:

```
2017 05 16 14:05:13#+00#ERROR#com.sap.iotservices.mms.ws.api.MqttService##anonymous#http-nio-8041-exec-11#na#WWWWWWWWW#iotmms#web##Parsing failed.java.io.EOFException: null
at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
at com.sap.iotservices.mms.ws.mqtt.ConnectMessage.(ConnectMessage.java:63)
at com.sap.iotservices.mms.ws.mqtt.Message.getMessage(Message.java:102)
at com.sap.iotservices.mms.ws.api.MqttService.handleMqttMessage(MqttService.java:165)
at com.sap.iotservices.mms.ws.api.MqttService.handleBinaryMessage(MqttService.java:156)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:71)
at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:589)
at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:549)
at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:67)
at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:204)
at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:203)
at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:93)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:635)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:805)
```

**Comment by davweiss** [comment]
I have resolved it with chaning the "sendPacket" method in "mqtt/lib/client.js" to

```
function sendPacket (client, packet, cb) {
  client.emit('packetsend', packet)
  var result = false
  try {
    var buf = mqttPacket.generate(packet)
    result = client.stream.write(buf)
  } catch (err){
    client.emit('error', err)
    result = false
  }
  if (!result && cb) {
    client.stream.once('drain', cb)
  } else if (cb) {
    cb()
  }
}
```

**Comment by jonmanzo** [comment]
@davweiss - You're my hero - also killed 3 days on this.

Basic info incase anyone with my specifics is searching.

AWS IOT Message Broker  - MQTT over WebSocket/TLS with SigV4 authentication using port 443

AWS IOT using updated -ast endpoints

Versions:
Node 10.2.1
mqtt v2.18.8
forced bumps to:
websocket-stream 5.1.2
duplexify 3.6.1
readable-stream 3.0.6

**Comment by jdevoo** [comment]
this change by @davweiss also helped me with https://dataflow.iot.att.com/

I had tried to fiddle with certificates, tls settings, etc. no luck. Paho Python and mosquitto_pub would work whereas MQTT.js gave me trouble.

- node v10.15.3
- mqtt 3.0.0

here's my connect code with the change (no 'ca' key under options)
```
var client  = mqtt.connect(dataflowHost, {
  clientId: apikey
})
```

here's the output (which goes into a reconnect loop) without the change from @davweiss using `NODE_DEBUG='net,tls' node server.js`
```
NET 30189: pipe false undefined
NET 30189: connect: find host mqtt.dataflow.iot.att.com
NET 30189: connect: dns options { family: undefined, hints: 32 }
NET 30189: _read
NET 30189: _read wait for connection
NET 30189: afterConnect
TLS 30189: start
NET 30189: _read
NET 30189: Socket._read readStart
TLS 30189: secure established
NET 30189: afterWrite 0
NET 30189: afterWrite call cb
NET 30189: destroy
NET 30189: close
NET 30189: close handle
NET 30189: emit close
on offline
on close
```

I had also successfully tested with https://test.mosquitto.org/ and their CRT on the 'ca' key in options.
```
NET 31458: pipe false undefined
NET 31458: connect: find host test.mosquitto.org
NET 31458: connect: dns options { family: undefined, hints: 32 }
NET 31458: _read
NET 31458: _read wait for connection
NET 31458: afterConnect
TLS 31458: start
NET 31458: _read
NET 31458: Socket._read readStart
TLS 31458: secure established
NET 31458: afterWrite 0
NET 31458: afterWrite call cb
Connected!
Uploading temperature data once per minute...
NET 31458: _read
^C
Disconnecting...
Exited!
```
