### ISSUE TITLE
Why is the client always disconnected from time to time?

### ISSUE THREAD

**Issue by arden** [mqttjs/MQTT.js#672]
Why is the client always disconnected from time to time? when the client recive message and publis message.

when the client publish a message, the client will trigger event 'offline/close/reconnect'.

```
2017-08-22T15:06:54+0800 <debug> app.js:88 (MqttClient.<anonymous>) offline
2017-08-22T15:06:54+0800 <debug> app.js:96 (MqttClient.<anonymous>) closed
2017-08-22T15:06:55+0800 <debug> app.js:100 (MqttClient.<anonymous>) reconnect
```

aedes's broker logs:

```
16:28:02.40 <debug> app.js:446 (Aedes.<anonymous>) client error a6d2024e0afd4fe3b8be14c63f56eb40 keep alive timeout Error: keep alive timeout
    at keepaliveTimeout (/mnt/data/webapps/ra-broker/node_modules/aedes/lib/handlers/connect.js:44:28)
    at Timeout.timerWrapper [as _onTimeout] (/mnt/data/webapps/ra-broker/node_modules/retimer/retimer.js:21:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by mcollina** [comment]
there can be a lot of reasons. you should check your broker logs.

**Comment by arden** [comment]
i'm use this code work fine:

```
client.publish('60/test', '手机用户', {qos:0, retain:false});
setTimeout(function(){
	client.publish('54/test', '手表用户54', {qos:0, retain:false});
	console.log('1');
}, 2000);
setTimeout(function(){
	client.publish('66/test', '手表用户66', {qos:0, retain:false});
	console.log('2');
}, 4000);
setTimeout(function(){
	client.publish('60/test', '手表用户60', {qos:0, retain:false});
	console.log('2');
}, 6000);
```

but i'm use this code can't work:

```
client.publish('54/test', '手表用户544', {qos:0, retain:false});
client.publish('66/test', '手表用户666', {qos:0, retain:false});
client.publish('60/test', '手表用户600', {qos:0, retain:false});
```

**Comment by jdiamond** [comment]
The aedes error you have says "keep alive timeout". That means your client disconnected without telling the server or is otherwise unable to send a PINGREQ packet before the server thinks the client is no longer present.

By default, MQTT.js sends a PINGREQ every 60 seconds. Did you disable it?

**Comment by arden** [comment]
i'm set every 30 seconds for sends PINGREQ to Aedes broker.

**Comment by arden** [comment]
@jdiamond 
the client.publish method cannot call continuously，must be called at intervals.

**Comment by jdiamond** [comment]
Below is an example that publishes 4 test messages in a row. It's not disconnecting for me. Can you modify it to demonstrate your issue?

```
const mqtt = require('mqtt');

console.log('connecting');

const client = mqtt.connect('mqtt://test.mosquitto.org');

client.on('connect', () => {
  console.log('connected');

  client.subscribe('test/1234');

  client.publish('test/1234', '1');
  client.publish('test/1234', '2');
  client.publish('test/1234', '3');
  client.publish('test/1234', '4');

  setTimeout(() => {
    console.log('disconnecting');
    client.end();
  }, 5000);
});

client.on('message', (topic, message) => {
  console.log(message.toString());
});

client.on('offline', () => {
  console.log('went offline');
});

client.on('error', () => {
  console.log('got error');
});

client.on('close', () => {
  console.log('connection closed');
});
```

**Comment by arden** [comment]
i'm found this problem, because i'm use Aedes as broker like this:

```
'use strict'

var mqemitterRedis = require('mqemitter-redis')
var mqRedis = mqemitterRedis({
  port: 6379,
  host: '127.0.0.1',
  password: '',
  db: 14,
  concurrency: 1000
})

var mqemitterMongodb = require('mqemitter-mongodb')
var mqMongodb = mqemitterMongodb({
  url: 'mongodb://127.0.0.1/mqemitter',
  concurrency: 1000
})

var persistenceRedis = require('aedes-persistence-redis')
var persistence = persistenceRedis({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: '',
  db: 14
})


// 这里如果用mq的话就会出现这个问题
// can't use mq
var aedes = require('./aedes')({
  //mq: mqRedis,
  //mq: mqMongodb,
  persistence: persistence,
  concurrency: 1000,
  heartbeatInterval: 1000,
  connectTimeout: 30000
})


//var aedes = require('./aedes')()

var server = require('net').createServer(aedes.handle)
var httpServer = require('http').createServer()
var ws = require('websocket-stream')
var port = 7000
var wsPort = 7001

server.listen(port, function () {
  console.log('server listening on port', port)
})

ws.createServer({
  server: httpServer
}, aedes.handle)

httpServer.listen(wsPort, function () {
  console.log('websocket server listening on port', wsPort)
})

aedes.on('clientError', function (client, err) {
  console.log('client error', client.id, err.message, err.stack)
})

aedes.on('publish', function (packet, client) {
  if (client) {
    console.log('message from client', client.id)
  }
})

aedes.on('subscribe', function (subscriptions, client) {
  if (client) {
    console.log('subscribe from client', subscriptions, client.id)
  }
})

aedes.on('client', function (client) {
  console.log('new client', client.id)
})
```

if i'm use mqemitter-redis or mqemitter-mongodb as Aedes's mq, the problem will appear.

```
// 这里如果用mq的话就会出现这个问题
// can't use mq
var aedes = require('./aedes')({
  //mq: mqRedis,
  //mq: mqMongodb,
  persistence: persistence,
  concurrency: 1000,
  heartbeatInterval: 1000,
  connectTimeout: 30000
})
```

why? why?

**Comment by NateZimmer** [comment]
I have a similar issue where the mqtt client is closing the socket then reconnecting on every pub.

```js

var period = 5000; // ms 

var mqtt = require('mqtt')
var client  = mqtt.connect('http://[myIP]:1883');
 
client.on('connect', function () {
      setInterval(()=>{
		client.publish('presence', 'Hello mqtt');  
	  },period)
});
 
```

**Comment by charles161** [comment]
I too had the same issue and I fixed it by setting the qos level of the message that is published other than zero. (I also use mqemitter-redis)
