### ISSUE TITLE
correct stop connection on wrong username or password

### ISSUE THREAD

**Issue by entcor** [mqttjs/MQTT.js#711]
hello !

How i can stop reconnection if server have returned auth error (code:4) ?
if i do:
```
                mqttclient.once('error', function (err) { 
			if (err.code == 4) 
				self.client.end(true);
		});
```
i got error like this:
```
Error: client disconnecting
    at MqttClient._checkDisconnecting (c:\develop\theRoomNodeClient\node_modules\mqtt\lib\client.js:333:16)
    at MqttClient.publish (c:\develop\theRoomNodeClient\node_modules\mqtt\lib\client.js:373:12)
    at theRoomBridge.mqemit (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:32:14)
    at CDataSet.sendData (c:\develop\theRoomNodeClient\node_modules\theroom\roomDataSet.js:90:22)
    at CDataSet.apply (c:\develop\theRoomNodeClient\node_modules\theroom\roomDataSet.js:130:7)
    at EventEmitter.theRoomStub.registerAction (c:\develop\theRoomNodeClient\node_modules\theroom\index.js:27:15)
    at c:\develop\theRoomNodeClient\client.js:24:7
    at Timeout._onTimeout (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:108:26)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
remoteCall:  Error: client disconnecting
    at MqttClient._checkDisconnecting (c:\develop\theRoomNodeClient\node_modules\mqtt\lib\client.js:333:16)
    at MqttClient.publish (c:\develop\theRoomNodeClient\node_modules\mqtt\lib\client.js:373:12)
    at theRoomBridge.<anonymous> (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:364:15)
    at theRoomBridge.remoteCall (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:360:9)
    at theRoomBridge.startRoom (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:407:14)
    at EventEmitter.theRoomStub.start (c:\develop\theRoomNodeClient\node_modules\theroom\index.js:21:64)
    at c:\develop\theRoomNodeClient\client.js:37:7
    at Timeout._onTimeout (c:\develop\theRoomNodeClient\node_modules\theroom\theRoomBridge.js:108:26)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
timeout
```

**Comment by mcollina** [comment]
Maybe it's a bug. Would you have time to do a PR?

**Comment by r3na** [comment]
@entcor  @mcollina   Was this fixed at any point? I also see this behavior happening on the latest version...

**Comment by r3na** [comment]
Nevermind.... the proposed solution solves the issue.
`if (err.code === 4 || err.code === 5)`

**Comment by YoDaMa** [comment]
@r3na which proposed solution?
