### ISSUE TITLE
[unhandled error] mqtt-packet throws if null topic

### ISSUE THREAD

**Issue by goliatone** [mqttjs/MQTT.js#742]
Errors thrown by [mqtt-packet](https://github.com/mqttjs/mqtt-packe) are not being handled by MQTT.js client. 

```
Error: Cannot parse topic at Parser._parsePublish (.../core.io-pubsub-mqtt/node_modules/mqtt-packet/parser.js:242:53)
at Parser._parsePayload (.../core.io-pubsub-mqtt/node_modules/mqtt-packet/parser.js:104:14)
at Parser.parse (.../core.io-pubsub-mqtt/node_modules/mqtt-packet/parser.js:37:48)
at Writable.writable._write (.../core.io-pubsub-mqtt/node_modules/mqtt/lib/client.js:270:12)
at doWrite (.../core.io-pubsub-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:406:64)
at writeOrBuffer (.../core.io-pubsub-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:395:5)
at Writable.write (.../core.io-pubsub-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:322:11)
 at Socket.ondata (_stream_readable.js:557:20)
 at emitOne (events.js:96:13)
 at Socket.emit (events.js:191:7)
 at readableAddChunk (_stream_readable.js:178:18)
 at Socket.Readable.push (_stream_readable.js:136:10)
 at TCP.onread (net.js:561:20)
---------------------------------------------
at Object.$initPubSubMQTT [as init] (.../core.io-pubsub-mqtt/lib/init.js:330:12)
at Application.register (.../application-core/lib/application.js:588:32)
at mountHandler (.../application-core/lib/application.js:473:25)
 at plugins.map (.../in/lib/in.js:268:41)
 at Array.map (native)
 at Promise (.../in/lib/in.js:268:25)
 at PluginLoader.mount (.../in/lib/in.js:266:16)
 at find.then.then.then.then (.../in/lib/in.js:307:37)
```

**Comment by goliatone** [comment]
I think this is because the event listener for error attached to the parser is added _after_ we pipe into the stream. 
In the **MqttClient** method `_setupStream`, if we move the [on('error')](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L288-L289) upwards, and register the handler **before** `this.stream.pipe(writable)`, we are good.

**Comment by RangerMauve** [comment]
@goliatone Would you be interested in contributing a pull request that fixes this and adds a test case?

**Comment by goliatone** [comment]
Sure. I did not see any tests to cover this case in the client.js test suit. 
For me, the complicated part will be to figure out how to test this behavior.

**Comment by RangerMauve** [comment]
Could you add a new test? Maybe create a fake stream as the connection and emit an invalid packet?
