### ISSUE TITLE
Problem with homebridge-mqtt

### ISSUE THREAD

**Issue by felipebraz** [mqttjs/MQTT.js#744]
Hi, I'm having some issues using mqttjs with homebridge-mqtt (https://github.com/cflurin/homebridge-mqtt). The homebridge-mqtt send a message with a strutucte like this:

{"name":"Luz Externa","service_name":"Luz Externa","characteristic":"On","value":false}

But when the message arrives on mqttjs I'm receiving the following error:

error: erro de sintaxe em ou próximo a "{"
    at Connection.parseE (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:114:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)

Translating from Portuguese:

error: syntax error near "{"
    at Connection.parseE (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/felipe/MQTT_Node/node_modules/pg/lib/connection.js:114:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)

Other softwares like Arduino and Mosquitto are receiving with no problems.
What could be happining?

**Comment by mcollina** [comment]
It seems the error is coming from pg, not really from the `pg` module, not really from MQTT.js

**Comment by felipebraz** [comment]
Weird, but there is no pg on my project... I'll review my code, sorry for the mistake
