### ISSUE TITLE
Fix typings please!

### ISSUE THREAD

**Issue by ArtemSkok** [mqttjs/MQTT.js#899]
Typings in this projects contain some kind of issues so that it is impossible to `import * as mqtt from 'mqtt';`

```console
> planttron.api@0.0.1 start:dev D:\projects\planttron\planttron.API
> set NODE_ENV=development&& ts-node ./src/startup.ts


D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/services/mqtt.service.ts(1,24): error TS2307: Cannot find module 'node_modules/mqtt/types/index'.

    at createTSError (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\projects\planttron\planttron.API\src\core\app.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\projects\planttron\planttron.API\node_modules\ts-node\src\index.ts:442:12)
```

**Comment by mcollina** [comment]
Please send a PR

Il giorno mar 11 dic 2018 alle 23:24 Artem Skok <notifications@github.com>
ha scritto:
