### ISSUE TITLE
How to catch"Not authorized" to prevent program to exit 

### ISSUE THREAD

**Issue by hkcity1111** [mqttjs/MQTT.js#905]
Hi,

I want to catch "Not authorized" error when I pass wrong accesstoken to MQTT server during auth but I did not succeed as follow. Did I get something wrong in my coding.
Thanks in advance.

Regards,
  Kenneth

```js
            var opts: mqtt.IClientOptions = {
                host: "192.168.1.10",
                port: 1833,
                username: "accesstokenpass"
            };

            try {

                var client = mqtt.connect(opts);
                console.log(`ThingsBoard after connnect`);                

                client.on('error',  () => {
                    console.log(`ThingsBoard MQTT Error`);                
                })
    
                client.on('message',  () => {
                    console.log(`ThingsBoard Message`);                
                    client.end();
                })            
    
                client.on('connect', () => {

                    client.publish("v1/devices/me/telemetry", JSON.stringify(telemetry));
                    client.end();
                })

            } catch (ex) {
                console.log(`ThingsBoard Error : ${ex}`);                

            }    
```

```

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\mqtt\lib\client.js:893:15)
    at MqttClient._handlePacket (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\mqtt\lib\client.js:329:12)
    at work (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\mqtt\lib\client.js:271:12)
    at Writable.writable._write (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\mqtt\lib\client.js:281:5)
    at doWrite (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (D:\Develop\iBeaconSensor\Espruino\src\MonitorApp\node_modules\readable-stream\lib\_stream_writable.js:334:11)
```

**Comment by millsy** [comment]
I have a similar scenario - failed auth kills the process

**Comment by ensleep** [comment]
I want to catch  "Not authorized" too!

**Comment by itishannuk** [comment]
I have the same problem when I restart my mqtt broker I see  "Not authorized" error when MQTT.js is reconnecting to broker

**Comment by YinHangCode** [comment]
````
client.on('error', (error) => {
    console.error(error);
});
````
