### ISSUE TITLE
"WS is not a constructor" - error after bundling with Webpack

### ISSUE THREAD

**Issue by murbanowicz** [mqttjs/MQTT.js#924]
Hi,
I came across this issue and cannot solve it so far.

It is backend app, but due to issues with Docker images size we have to bundle it with Webpack.

It is working fine without bundling.

Stuff which I think matters:

**error:**
```
    TypeError: WS is not a constructor
        at WebSocketStream (dist/index.js:159329:16)
        at createWebSocket (dist/index.js:147450:10)
        at Object.buildBuilderBrowser (dist/index.js:147476:10)
        at MqttClient.wrapper [as streamBuilder] (dist/index.js:147937:36)
        at MqttClient._setupStream (dist/index.js:146471:22)
        at new MqttClient (dist/index.js:146452:8)
        at Function.connect (dist/index.js:147940:10)

```

**webpack config:**
```js
const path = require('path');
const nodeExternals = require('webpack-node-externals');

const { NODE_ENV = 'production' } = process.env;

module.exports = {
  entry: { index: './src/index.ts' },
  mode: NODE_ENV,
  target: 'node',
  watch: NODE_ENV === 'development',
  externals: [nodeExternals()],
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js',
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  node: {
    __dirname: false,
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [{ loader: 'ts-loader', options: { transpileOnly: true } }],
      },
      {
        test: /(\.md|\.map)$/,
        loader: 'null-loader',
      },
    ],
  },
};
```

Function where it happens:
```js
createMqttClient(): MqttClient {
    return mqtt.connect(this.mqttOptions.url, { ...this.mqttOptions.options });
  }
```

The url is like: `ssl://url-to-our-mqtt`

Can anybody help please?

**Comment by ucheol2** [comment]
You should rather import `mqtt` in this way

```
import { connect, MqttClient } from 'mqtt'
```

not this way

```
import mqtt from 'mqtt'
...
mqtt.connect 
```

**Comment by xuhongv** [comment]
试下这个已经集成MQTT.js库的开源项目：https://github.com/xuhongv/WeChatMiniEsp8266
